/**
 * This file was auto-generated by openapi-typescript.
 * Do not make direct changes to the file.
 */

export interface paths {
    "/api/v1/auth/demo-login": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Demo Login */
        post: operations["demo_login_api_v1_auth_demo_login_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/logout": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Logout */
        post: operations["logout_api_v1_auth_logout_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/auth/personas": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Personas */
        get: operations["personas_api_v1_auth_personas_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/config": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Public Config */
        get: operations["public_config_api_v1_config_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/development/courses": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Courses */
        get: operations["courses_api_v1_development_courses_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/development/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Tracks */
        get: operations["tracks_api_v1_development_tracks_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/ecosystem/events": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Event Catalog */
        get: operations["event_catalog_api_v1_ecosystem_events_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Me */
        get: operations["me_api_v1_me_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/active-role": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Switch Role */
        post: operations["switch_role_api_v1_me_active_role_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/consents/{scope}": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        /** Set Consent */
        put: operations["set_consent_api_v1_me_consents__scope__put"];
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/courses/{course_key}/completion": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report Completion */
        post: operations["report_completion_api_v1_me_courses__course_key__completion_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/courses/{course_key}/learning-days": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Record Learning Day */
        post: operations["record_learning_day_api_v1_me_courses__course_key__learning_days_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/event-claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Participant Claims */
        get: operations["participant_claims_api_v1_me_event_claims_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/event-claims/{claim_id}/submit": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Submit Claim */
        post: operations["submit_claim_api_v1_me_event_claims__claim_id__submit_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/events/{event_key}/claims": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Report Claim */
        post: operations["report_claim_api_v1_me_events__event_key__claims_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/learning/streak": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Streak */
        get: operations["streak_api_v1_me_learning_streak_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/roadmaps": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /** Roadmaps */
        get: operations["roadmaps_api_v1_me_roadmaps_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/me/tracks": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Select Track */
        post: operations["select_track_api_v1_me_tracks_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/event-claims/import": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Import Claim */
        post: operations["import_claim_api_v1_operations_event_claims_import_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/api/v1/operations/event-claims/{claim_id}/decision": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        get?: never;
        put?: never;
        /** Decide Claim */
        post: operations["decide_claim_api_v1_operations_event_claims__claim_id__decision_post"];
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
    "/health/live": {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        /**
         * Live
         * @description Return success while the process event loop is responsive.
         */
        get: operations["live_health_live_get"];
        put?: never;
        post?: never;
        delete?: never;
        options?: never;
        head?: never;
        patch?: never;
        trace?: never;
    };
}
export type webhooks = Record<string, never>;
export interface components {
    schemas: {
        /** ActorView */
        ActorView: {
            active_role: components["schemas"]["Role"];
            /** Assigned Roles */
            assigned_roles: components["schemas"]["Role"][];
            /** Consent Scopes */
            consent_scopes: components["schemas"]["ConsentScope"][];
            /** Csrf Token */
            csrf_token?: string | null;
            /** Display Name */
            display_name: string;
            /** Navigation */
            navigation: string[];
            /**
             * Person Id
             * Format: uuid
             */
            person_id: string;
            /** Scopes */
            scopes: string[];
        };
        /**
         * ClaimStatus
         * @enum {string}
         */
        ClaimStatus: "reported" | "awaiting_verification" | "verified" | "rejected" | "revoked";
        /** ClaimView */
        ClaimView: {
            /** Claim Type */
            claim_type: string;
            /** Event Key */
            event_key: string;
            /**
             * Id
             * Format: uuid
             */
            id: string;
            status: components["schemas"]["ClaimStatus"];
            /** Trophy Created */
            trophy_created: boolean;
            /** Verification Explanation */
            verification_explanation: string;
        };
        /**
         * CompletionStatus
         * @enum {string}
         */
        CompletionStatus: "reported" | "verified" | "rejected";
        /** CompletionView */
        CompletionView: {
            /** Course Key */
            course_key: string;
            /** Explanation */
            explanation: string;
            /** Rating Eligible */
            rating_eligible: boolean;
            status: components["schemas"]["CompletionStatus"];
        };
        /** ConsentRequest */
        ConsentRequest: {
            /** Granted */
            granted: boolean;
        };
        /**
         * ConsentScope
         * @enum {string}
         */
        ConsentScope: "public_rating" | "public_trophies" | "public_profile" | "hr_profile" | "ai_memory" | "course_honor_board";
        /** ConsentView */
        ConsentView: {
            /** Granted */
            granted: boolean;
            /** Granted Scopes */
            granted_scopes: components["schemas"]["ConsentScope"][];
            scope: components["schemas"]["ConsentScope"];
        };
        /** CourseView */
        CourseView: {
            /** Access Note */
            access_note: string;
            /** Availability */
            availability: string;
            /** Completion Status */
            completion_status: string | null;
            /** Key */
            key: string;
            /** Rating Eligible */
            rating_eligible: boolean;
            /** Recommendation Reason */
            recommendation_reason: string;
            /** Source Url */
            source_url: string;
            /** Title */
            title: string;
            /** Track Keys */
            track_keys: string[];
        };
        /** CursorPage[EventView] */
        CursorPage_EventView_: {
            /**
             * Has More
             * @default false
             */
            has_more: boolean;
            /** Items */
            items: components["schemas"]["EventView"][];
            /** Next Cursor */
            next_cursor?: string | null;
        };
        /** DecisionRequest */
        DecisionRequest: {
            /** Reason */
            reason: string;
            /**
             * Status
             * @enum {string}
             */
            status: "verified" | "rejected" | "revoked";
        };
        /** DemoLoginRequest */
        DemoLoginRequest: {
            /** Persona Key */
            persona_key: string;
        };
        /** EventView */
        EventView: {
            /** Conditions */
            conditions: string;
            /** Deadline At */
            deadline_at: string | null;
            /** Event Type */
            event_type: string;
            /** Key */
            key: string;
            /** Organizer */
            organizer: string;
            /** Recommendation Reason */
            recommendation_reason: string;
            /**
             * Source Checked At
             * Format: date-time
             */
            source_checked_at: string;
            /** Source Status */
            source_status: string;
            /** Source Url */
            source_url: string;
            /** Starts At */
            starts_at: string | null;
            /** Status */
            status: string;
            /** Title */
            title: string;
            /** Track Keys */
            track_keys: string[];
        };
        /** HTTPValidationError */
        HTTPValidationError: {
            /** Detail */
            detail?: components["schemas"]["ValidationError"][];
        };
        /** ImportClaimRequest */
        ImportClaimRequest: {
            /**
             * Claim Type
             * @default participation
             * @enum {string}
             */
            claim_type: "participation" | "winner" | "prize";
            /** Event Key */
            event_key: string;
            /** External Id */
            external_id: string;
            /** Person External Key */
            person_external_key: string;
            /** Provider Id */
            provider_id: string;
        };
        /** LearningDayRequest */
        LearningDayRequest: {
            /**
             * Occurred At
             * Format: date-time
             */
            occurred_at: string;
        };
        /**
         * LiveResponse
         * @description Stable liveness response.
         */
        LiveResponse: {
            /**
             * Status
             * @default ok
             * @constant
             */
            status: "ok";
        };
        /** MilestoneView */
        MilestoneView: {
            /** Completed */
            completed: boolean;
            /** Key */
            key: string;
            /** Position */
            position: number;
            /** Purpose */
            purpose: string;
            /** Skill */
            skill: string;
            /** Target Key */
            target_key: string;
            /** Target Kind */
            target_kind: string;
            /** Title */
            title: string;
        };
        /** PersonaView */
        PersonaView: {
            /** Display Name */
            display_name: string;
            /** Key */
            key: string;
            /** Roles */
            roles: components["schemas"]["Role"][];
        };
        /** ReportClaimRequest */
        ReportClaimRequest: {
            /**
             * Claim Type
             * @default participation
             * @enum {string}
             */
            claim_type: "participation" | "winner" | "prize";
        };
        /** RoadmapView */
        RoadmapView: {
            /** Milestones */
            milestones: components["schemas"]["MilestoneView"][];
            next_step: components["schemas"]["MilestoneView"] | null;
            /** Policy Version */
            policy_version: number;
            /** Replacement Reason */
            replacement_reason: string | null;
            /** Track Key */
            track_key: string;
        };
        /**
         * Role
         * @enum {string}
         */
        Role: "participant" | "mentor" | "customer" | "manager" | "hr" | "operator";
        /** SelectTrackRequest */
        SelectTrackRequest: {
            /** Freeze Track Key */
            freeze_track_key?: string | null;
            /** Track Key */
            track_key: string;
        };
        /** StreakView */
        StreakView: {
            /** Current Days */
            current_days: number;
            /** Qualified Dates */
            qualified_dates: string[];
            /** Reason */
            reason: string;
        };
        /** SwitchRoleRequest */
        SwitchRoleRequest: {
            role: components["schemas"]["Role"];
        };
        /** TrackOverview */
        TrackOverview: {
            /** Active Count */
            active_count: number;
            /**
             * Max Active
             * @default 2
             */
            max_active: number;
            /** Tracks */
            tracks: components["schemas"]["TrackView"][];
        };
        /**
         * TrackStatus
         * @enum {string}
         */
        TrackStatus: "active" | "frozen";
        /** TrackView */
        TrackView: {
            /** Completed Milestones */
            completed_milestones: string[];
            /** Key */
            key: string;
            status: components["schemas"]["TrackStatus"] | null;
            /** Title */
            title: string;
        };
        /** ValidationError */
        ValidationError: {
            /** Context */
            ctx?: Record<string, never>;
            /** Input */
            input?: unknown;
            /** Location */
            loc: (string | number)[];
            /** Message */
            msg: string;
            /** Error Type */
            type: string;
        };
    };
    responses: never;
    parameters: never;
    requestBodies: never;
    headers: never;
    pathItems: never;
}
export type $defs = Record<string, never>;
export interface operations {
    demo_login_api_v1_auth_demo_login_post: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DemoLoginRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActorView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    logout_api_v1_auth_logout_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            204: {
                headers: {
                    [name: string]: unknown;
                };
                content?: never;
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    personas_api_v1_auth_personas_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["PersonaView"][];
                };
            };
        };
    };
    public_config_api_v1_config_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": {
                        [key: string]: boolean | string;
                    };
                };
            };
        };
    };
    courses_api_v1_development_courses_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CourseView"][];
                };
            };
        };
    };
    tracks_api_v1_development_tracks_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackOverview"];
                };
            };
        };
    };
    event_catalog_api_v1_ecosystem_events_get: {
        parameters: {
            query?: {
                track?: string | null;
                event_type?: string | null;
                status?: string | null;
                cursor?: string | null;
                limit?: number;
            };
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CursorPage_EventView_"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    me_api_v1_me_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActorView"];
                };
            };
        };
    };
    switch_role_api_v1_me_active_role_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SwitchRoleRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ActorView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    set_consent_api_v1_me_consents__scope__put: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                scope: components["schemas"]["ConsentScope"];
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ConsentRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ConsentView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_completion_api_v1_me_courses__course_key__completion_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                course_key: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["CompletionView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    record_learning_day_api_v1_me_courses__course_key__learning_days_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                course_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["LearningDayRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreakView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    participant_claims_api_v1_me_event_claims_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimView"][];
                };
            };
        };
    };
    submit_claim_api_v1_me_event_claims__claim_id__submit_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                claim_id: string;
            };
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    report_claim_api_v1_me_events__event_key__claims_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                event_key: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ReportClaimRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    streak_api_v1_me_learning_streak_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["StreakView"];
                };
            };
        };
    };
    roadmaps_api_v1_me_roadmaps_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["RoadmapView"][];
                };
            };
        };
    };
    select_track_api_v1_me_tracks_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["SelectTrackRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["TrackOverview"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    import_claim_api_v1_operations_event_claims_import_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path?: never;
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["ImportClaimRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    decide_claim_api_v1_operations_event_claims__claim_id__decision_post: {
        parameters: {
            query?: never;
            header?: {
                "X-CSRF-Token"?: string | null;
            };
            path: {
                claim_id: string;
            };
            cookie?: never;
        };
        requestBody: {
            content: {
                "application/json": components["schemas"]["DecisionRequest"];
            };
        };
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["ClaimView"];
                };
            };
            /** @description Validation Error */
            422: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["HTTPValidationError"];
                };
            };
        };
    };
    live_health_live_get: {
        parameters: {
            query?: never;
            header?: never;
            path?: never;
            cookie?: never;
        };
        requestBody?: never;
        responses: {
            /** @description Successful Response */
            200: {
                headers: {
                    [name: string]: unknown;
                };
                content: {
                    "application/json": components["schemas"]["LiveResponse"];
                };
            };
        };
    };
}
