import { useQuery } from "@tanstack/react-query";

import { apiRequest } from "../api/client";
import { Badge, StatePanel } from "../components/ui";

type Stage = { key: string; title: string; status: "completed" | "in_progress" | "not_started" | "unknown"; completed: boolean; count: number };
type Earnings = { calculated: string; approved: string; paid: string; failed: string; currency: string | null; unknown_items: number };
type Analytics = { stages: Stage[]; successful: boolean; next_action: string; earnings: Earnings; freshness: string; generated_at: string };
type Role = "mentor" | "customer" | "manager" | "hr" | "operator";
type Metric = { key: string; label: string; numerator: number; denominator: number; value: string | null; unit: "percent" | "count"; period_start: string; period_end: string; cohort: string; freshness: "fresh" | "stale" | "unknown"; definition: string; suppressed: boolean; suppression_reason: string | null };
type RoleAnalyticsData = { role: Role; metrics: Metric[] };
const money = (value: string, currency: string | null) => `${Number(value).toLocaleString("ru-RU")} ${currency ?? "₽"}`;
const demoAnalytics: Analytics = {
  stages: [
    { key: "learning", title: "Обучение", status: "completed", completed: true, count: 6 },
    { key: "applications", title: "Отклики", status: "completed", completed: true, count: 4 },
    { key: "work", title: "Работа", status: "completed", completed: true, count: 3 },
    { key: "accepted", title: "Принятый результат", status: "completed", completed: true, count: 2 },
    { key: "paid", title: "Выплата", status: "in_progress", completed: false, count: 1 },
  ],
  successful: true,
  next_action: "Завершить MVP рекомендательной системы и отправить артефакты до 12 октября",
  earnings: { calculated: "225000", approved: "200000", paid: "125000", failed: "0", currency: "RUB", unknown_items: 0 },
  freshness: "fresh", generated_at: "2026-09-28T12:00:00Z",
};

export function ParticipantAnalytics() {
  const query = useQuery({ queryKey: ["participant-analytics"], queryFn: () => apiRequest<Analytics>("/api/v1/me/analytics/journey"), refetchOnMount: "always" });
  if (query.isLoading) return <StatePanel kind="loading" />;
  const data = query.data ?? demoAnalytics;
  const earnings = [{ key: "calculated", title: "Рассчитано", value: data.earnings.calculated }, { key: "approved", title: "Одобрено", value: data.earnings.approved }, { key: "paid", title: "Выплачено", value: data.earnings.paid }, { key: "failed", title: "Ошибка выплаты", value: data.earnings.failed }];
  const activity = [42, 58, 51, 73, 66, 88, 79, 94];
  return <div className="feature-stack participant-analytics analytics-dashboard">
    {query.isError && <div className="demo-fallback-note" role="status"><strong>Демонстрационная аналитика</strong><span>API временно недоступен — показана связанная mock-проекция.</span><button className="secondary-button" type="button" onClick={() => { void query.refetch(); }}>Повторить</button></div>}
    <header className="dashboard-heading"><div><p className="eyebrow">Аналитика · личный путь</p><h1 id="workspace-title">Ваш прогресс и подтверждённый результат</h1><p className="lead">Показываем, как обучение превращается в проекты, оценки, выплаты и позицию в рейтинге.</p></div><div className="analytics-controls"><label>Период<select defaultValue="90"><option value="30">30 дней</option><option value="90">3 месяца</option><option value="season">Сезон</option></select></label><label>Направление<select defaultValue="all"><option value="all">Все</option><option value="python">Python</option><option value="data">Data</option></select></label><div className="freshness-chip"><span className="fresh-dot" />Обновлено сегодня</div></div></header>
    <section className="competency-overview"><div className="competency-main"><div className="section-heading"><div><p className="eyebrow">Главный результат развития</p><h2>Матрица компетенций · Python-разработчик</h2></div><Badge tone="success">Готовность 72%</Badge></div><p>Уровни основаны на проверенных курсах и принятом проектном вкладе. Нажмите на навык, чтобы увидеть доказательства.</p><div className="competency-matrix">{[
      ["Python", "Уверенный", 82, "Курс + 2 проекта"],
      ["API и интеграции", "Уверенный", 76, "Checkpoint + проект"],
      ["Тестирование", "Базовый", 54, "Курс · нужна практика"],
      ["OpenSpec / SDD", "Уверенный", 71, "Сертификат курса"],
      ["Командная работа", "Подтверждён", 88, "2 оценки заказчика"],
    ].map(([skill, level, progress, evidence]) => <button type="button" key={String(skill)}><span><strong>{skill}</strong><small>{evidence}</small></span><i><b style={{ width: `${String(progress)}%` }} /></i><em>{level}</em></button>)}</div></div><aside className="credential-summary"><p className="eyebrow">Документы</p><h2>3 подтверждения</h2><article><span>✓</span><div><strong>OpenSpec и SDD</strong><small>Сертификат курса · valid</small></div></article><article><span>✓</span><div><strong>Python для R&amp;D</strong><small>Сертификат курса · valid</small></div></article><article><span>◆</span><div><strong>Прогнозирование нагрузки</strong><small>Проектный опыт · оценка B</small></div></article><button type="button">Открыть все сертификаты</button><div className="readiness-gap"><strong>До следующего уровня</strong><p>Завершите проектный checkpoint по автоматическим тестам.</p><span>+12% к готовности роли</span></div></aside></section>
    <section className="metric-grid"><article className="metric-card metric-card--teal"><span>Прогресс траектории</span><strong>68%</strong><small>+12% за месяц</small></article><article className="metric-card metric-card--blue"><span>Активные проекты</span><strong>2</strong><small>1 результат до 12 октября</small></article><article className="metric-card metric-card--violet"><span>Подтверждённый опыт</span><strong>7</strong><small>2 оценки A · 3 оценки B</small></article><article className="metric-card metric-card--teal"><span>Выплачено</span><strong>125 000 ₽</strong><small>225 000 ₽ рассчитано</small></article></section>
    <div className="analytics-main-grid"><section className="analytics-panel"><div className="section-heading"><div><p className="eyebrow">Конверсия пути</p><h2>От обучения до выплаты</h2></div><Badge tone="success">42% до результата</Badge></div><div className="analytics-funnel">{[{ label: "Обучение", value: 12, rate: "100%" }, { label: "Отклики", value: 8, rate: "67%" }, { label: "Работа", value: 5, rate: "63%" }, { label: "Принято", value: 3, rate: "60%" }, { label: "Выплачено", value: 2, rate: "67%" }].map((stage, index) => <div key={stage.label} style={{ width: `${String(100 - index * 11)}%` }}><span>{stage.label}</span><strong>{stage.value}</strong><small>{stage.rate}</small></div>)}</div></section>
      <section className="analytics-panel"><div className="section-heading"><div><p className="eyebrow">Динамика</p><h2>Активность по неделям</h2></div><Badge>8 недель</Badge></div><div className="analytics-histogram" role="img" aria-label="Активность по восьми неделям">{activity.map((value, index) => <div key={index}><i style={{ height: `${String(value)}%` }} /><span>Н{index + 1}</span><small>{value}</small></div>)}</div></section></div>
    <div className="analytics-main-grid"><section className="analytics-panel"><h2>Баллы и рейтинг</h2><div className="score-split"><div><span>Постоянные</span><strong>450</strong><small>Принятые проекты и подтверждённые события</small></div><div><span>Замороженные</span><strong>+5</strong><small>AI Journey 2026 · до проверки результата</small></div><div><span>Позиция</span><strong>3 → 2</strong><small>50 баллов до следующего места</small></div></div></section><section className="analytics-panel"><h2>Распределение результата</h2><div className="direction-bars"><div><span>Python / Backend</span><i><b style={{ width: "74%" }} /></i><strong>74%</strong></div><div><span>Data / ML</span><i><b style={{ width: "18%" }} /></i><strong>18%</strong></div><div><span>Product</span><i><b style={{ width: "8%" }} /></i><strong>8%</strong></div></div></section></div>
    <section className="learning-effectiveness"><div><p className="eyebrow">Эффективность обучения</p><h2>Навыки применяются в реальных проектах</h2></div><div><strong>18</strong><span>checkpoint завершено</span></div><div><strong>42 ч</strong><span>осмысленного обучения</span></div><div><strong>3</strong><span>курса подтверждено</span></div><div><strong>78%</strong><span>навыков применено</span></div></section>
    <section className="analytics-results"><div className="section-heading"><h2>Последние подтверждённые результаты</h2><Badge tone="success">Проверены человеком</Badge></div><article><strong>Рекомендательная система</strong><span>Оценка A · 125 000 ₽ · +150 баллов</span></article><article><strong>Прогнозирование нагрузки</strong><span>Оценка B · 75 000 ₽ · +90 баллов</span></article></section>
    <section className="analytics-ai-insight"><span className="ai-orb">✦</span><div><p className="eyebrow">AI insight · не решение</p><h2>{data.next_action}</h2><p>Checkpoint связан с текущим проектом и даст максимальный прирост подтверждённого опыта на этой неделе.</p></div><Badge tone={data.successful ? "success" : "warning"}>{data.successful ? "Путь подтверждён" : "Путь продолжается"}</Badge></section>
    <section><div className="section-heading"><div><p className="eyebrow">Вознаграждение</p><h2>Начисления и выплаты</h2></div></div><div className="earnings-grid">{earnings.map((item) => <article className={`earning-card earning-card--${item.key}`} key={item.key}><span>{item.title}</span><strong>{money(item.value, data.earnings.currency)}</strong><small>{item.key === "paid" ? "Фактически переведено" : item.key === "failed" ? "Требует внимания" : "Статус расчёта"}</small></article>)}</div></section>
  </div>;
}

const roleTitles: Record<Role, string> = { mentor: "Качество и скорость ревью", customer: "Путь задачи до принятого результата", manager: "Результаты и повторное использование", hr: "Воронка кандидатов по решениям людей", operator: "Качество операционного контура" };

export function RoleAnalytics({ role }: { role: Role }) {
  const query = useQuery({ queryKey: ["role-analytics", role], queryFn: () => apiRequest<RoleAnalyticsData>("/api/v1/analytics/role"), refetchOnMount: "always" });
  if (query.isLoading) return <StatePanel kind="loading" />;
  if (query.isError || !query.data) return <StatePanel kind="error" action="Повторить" onAction={() => { void query.refetch(); }} />;
  const stale = query.data.metrics.some((metric) => metric.freshness !== "fresh");
  return <div className="feature-stack role-analytics"><header className="dashboard-heading"><div><p className="eyebrow">Аналитика роли · проверяемые формулы</p><h1 id="workspace-title">{roleTitles[role]}</h1><p className="lead">Каждое значение показывает период, когорту, числитель и знаменатель. Подавленные или задержанные данные не заменяются нулём.</p></div><Badge tone={stale ? "warning" : "success"}>{stale ? "Данные задерживаются" : "Данные актуальны"}</Badge></header>{stale && <div className="analytics-stale" role="status"><strong>Источник обновляется с задержкой</strong><span>Последнее доступное значение сохранено; нулевой результат не подставляется.</span></div>}<section className="role-metric-grid" aria-label="Метрики роли">{query.data.metrics.map((metric) => <article className={`role-metric-card ${metric.suppressed ? "role-metric-card--suppressed" : ""}`} key={metric.key}><header><span>{metric.label}</span><Badge tone={metric.freshness === "fresh" ? "success" : "warning"}>{metric.freshness === "fresh" ? "Актуально" : "Задержка"}</Badge></header><strong>{metric.suppressed ? "Скрыто" : metric.value === null ? "Нет данных" : metric.unit === "percent" ? `${metric.value}%` : metric.value}</strong><small>{new Date(metric.period_start).toLocaleDateString("ru-RU")} — {new Date(metric.period_end).toLocaleDateString("ru-RU")}</small><details><summary>Как рассчитано</summary><p>{metric.definition}</p><dl><div><dt>Числитель</dt><dd>{metric.suppressed ? "—" : metric.numerator}</dd></div><div><dt>Знаменатель</dt><dd>{metric.suppressed ? "—" : metric.denominator}</dd></div><div><dt>Когорта</dt><dd>{metric.cohort}</dd></div></dl>{metric.suppressed && <p className="privacy-note">Малая когорта: значение и персональная детализация скрыты.</p>}</details></article>)}</section></div>;
}
