import { useEffect, useState } from "react";
import { useNavigate, useSearchParams } from "react-router-dom";

type Section = "Главная" | "Мои задачи" | "Создать задачу" | "Заявки" | "Приёмка" | "Аналитика" | "AI-помощник" | "Кандидаты" | "Сообщения";
type Page = Section | "Задача" | "Профиль";
type Task = { id: string; title: string; department: string; direction: string; problem: string; deliverable: string; criteria: string; deadline: string; status: "draft" | "published" | "in_progress" | "review" | "completed"; mode: "open" | "invitation_only"; places: number; version: number };
type Application = { taskId: string; candidateId: string; status: "applied" | "shortlisted" | "waitlisted" | "assigned" };
type Result = { taskId: string; candidateId: string; summary: string; artifact: string; status: "submitted" | "accepted" | "revision" | "disputed"; comment: string };
type Case = { title: string; artifact: string; skills: string[]; expert?: string; completedAt?: string; rubric?: Record<string, number> };
type Candidate = { id: string; name: string; direction: string; mentor?: string; education?: string; city?: string; courses?: string[]; cases: Case[] };
type Message = { taskId: string; author: string; body: string; candidateId?: string };
type Scenario = { tasks: Task[]; applications: Application[]; results: Result[]; candidates: Candidate[]; saved: string[]; invited: string[]; interviews: string[]; messages: Message[]; taskInvitations?: { taskId: string; candidateId: string }[] };
const pages: Section[] = ["Главная", "Мои задачи", "Создать задачу", "Заявки", "Приёмка", "Аналитика", "AI-помощник", "Кандидаты", "Сообщения"];
const today = new Date();
const later = (days: number) => new Date(today.getTime() + days * 86400000).toISOString().slice(0, 10);
const seed: Scenario = {
  tasks: [
    { id: "IMP-101", title: "Прогноз загрузки отделений", department: "Розничный бизнес", direction: "Аналитика данных", problem: "Спрогнозировать нагрузку на отделения по обезличенным историческим данным", deliverable: "Отчёт, воспроизводимый ноутбук и презентация", criteria: "Качество прогноза, воспроизводимость и объяснение ошибок", deadline: later(21), status: "review", mode: "open", places: 2, version: 1 },
    { id: "IMP-102", title: "Классификация обращений", department: "Клиентский сервис", direction: "AI / ML", problem: "Сократить время маршрутизации обращений", deliverable: "Прототип классификатора, демо и инструкция", criteria: "Macro F1, задержка ответа и анализ неоднозначных случаев", deadline: later(36), status: "in_progress", mode: "open", places: 2, version: 1 },
    { id: "IMP-103", title: "Анализ качества поисковой выдачи", department: "R&D", direction: "Аналитика данных", problem: "Найти причины нерелевантных ответов внутреннего поиска", deliverable: "Исследование, метрики и рекомендации", criteria: "Обоснованность выборки и проверяемость выводов", deadline: later(50), status: "published", mode: "open", places: 3, version: 1 },
    { id: "IMP-104", title: "Исследование прогноза спроса", department: "Розничный бизнес", direction: "Аналитика данных", problem: "Проверить гипотезы о сезонности спроса", deliverable: "Исследование с воспроизводимыми расчётами", criteria: "Воспроизводимость и обоснованность прогноза", deadline: later(60), status: "published", mode: "invitation_only", places: 2, version: 1 },
  ],
  candidates: [
    { id: "p1", name: "Мария Ковалёва", direction: "Аналитика данных", mentor: "Елена Волкова", education: "МФТИ · прикладная математика", city: "Москва", courses: ["Аналитика данных", "Python для исследований"], cases: [{ title: "Прогноз загрузки отделений", artifact: "Отчёт и ноутбук · принят заказчиком", skills: ["Python", "прогнозирование", "защита решения"], expert: "Елена Волкова", completedAt: "2026-09-12", rubric: { "Результат": 88, "Ход мысли": 82, "Неопределённость": 74, "Использование ИИ": 77, "Защита решения": 84 } }] },
    { id: "p2", name: "Иван Петров", direction: "AI / ML", mentor: "Андрей Ким", education: "НИУ ВШЭ · компьютерные науки", city: "Санкт-Петербург", courses: ["Основы ML"], cases: [{ title: "Классификация обращений", artifact: "Прототип и разбор ошибок · принят заказчиком", skills: ["NLP", "оценка модели", "работа с неопределённостью"], expert: "Андрей Ким", completedAt: "2026-09-18", rubric: { "Результат": 85, "Ход мысли": 79, "Неопределённость": 81, "Использование ИИ": 83, "Защита решения": 76 } }] },
    { id: "p3", name: "Алина Сергеева", direction: "Аналитика данных", mentor: "Ольга Морозова", education: "ИТМО · системный анализ", city: "Москва", courses: ["SQL для аналитиков"], cases: [{ title: "Исследование клиентского пути", artifact: "Отчёт и презентация · приняты заказчиком", skills: ["SQL", "аналитика", "аргументация"], expert: "Ольга Морозова", completedAt: "2026-09-20", rubric: { "Результат": 86, "Ход мысли": 90, "Неопределённость": 72, "Использование ИИ": 68, "Защита решения": 87 } }] },
  ],
  applications: [{ taskId: "IMP-101", candidateId: "p1", status: "assigned" }, { taskId: "IMP-102", candidateId: "p2", status: "assigned" }, { taskId: "IMP-103", candidateId: "p3", status: "applied" }],
  results: [{ taskId: "IMP-101", candidateId: "p1", summary: "Модель прогноза и анализ ошибок по сегментам", artifact: "Отчёт · ноутбук · презентация", status: "submitted", comment: "" }],
  saved: [], invited: [], interviews: [], taskInvitations: [], messages: [{ taskId: "IMP-101", author: "Мария Ковалёва", candidateId: "p1", body: "Отправила отчёт и воспроизводимый ноутбук на проверку." }],
};
const key = "impulse-customer-pilot-v1";
function initial(): Scenario { try { const value = localStorage.getItem(key); if (!value) return seed; const saved = JSON.parse(value) as Scenario; return { ...seed, ...saved, candidates: seed.candidates.map((person) => ({ ...person, ...saved.candidates.find((item) => item.id === person.id), cases: person.cases })), taskInvitations: saved.taskInvitations ?? [] }; } catch { return seed; } }
const status = { draft: "Черновик", published: "Опубликована", in_progress: "В работе", review: "На проверке", completed: "Завершена" };
const name = (state: Scenario, id: string) => state.candidates.find((person) => person.id === id)?.name ?? "Участник";

function CustomerTaskList({ state, filter, onFilter, onOpen }: { state: Scenario; filter: string; onFilter: (value: string) => void; onOpen: (id: string) => void }) {
  const filters = ["Все", "Опубликована", "В работе", "На проверке", "Завершена", "Черновик"];
  const tasks = state.tasks.filter((item) => filter === "Все" || status[item.status] === filter);
  return <section className="task-marketplace customer-task-marketplace" aria-labelledby="customer-list-title">
    <div className="section-heading marketplace-heading"><div><p className="eyebrow">Портфель заказчика</p><h2 id="customer-list-title">Мои задачи</h2><p className="lead">Все задачи команды: от черновика до принятого результата.</p></div><span className="ui-badge ui-badge--info">{tasks.length} задач</span></div>
    <div className="task-filter-row" role="group" aria-label="Фильтр задач">{filters.map((item) => <button type="button" key={item} className={filter === item ? "active" : ""} aria-pressed={filter === item} onClick={() => { onFilter(item); }}>{item}</button>)}</div>
    <div className="participant-task-list customer-task-list">{tasks.length ? tasks.map((item, index) => {
      const assigned = state.applications.filter((entry) => entry.taskId === item.id && entry.status === "assigned").length;
      const applications = state.applications.filter((entry) => entry.taskId === item.id).length;
      return <article className="participant-task-row" key={item.id}>
        <span className={`task-kind-icon task-kind-icon--${String(index % 3)}`} aria-hidden="true">▤</span>
        <div className="task-list-main"><div><small>{item.id} · {item.direction}</small></div><strong>{item.title}</strong><p>{item.department} · {item.mode === "invitation_only" ? "По приглашению" : "Открытая задача"}</p></div>
        <span className="customer-task-state">{status[item.status]}</span>
        <div className="task-list-deadline"><small>Срок</small><strong>{item.deadline}</strong><small>Заявок {applications} · в работе {assigned}</small></div>
        <div className="task-list-action"><button type="button" onClick={() => { onOpen(item.id); }}>Открыть задачу</button></div>
      </article>;
    }) : <div className="empty-application"><strong>Задач с этим статусом нет</strong><p>Выберите другой фильтр.</p></div>}</div>
  </section>;
}

function CustomerTaskDetail({ task, state, onBack, onProfile, onMessages, onApplications, onResults, onRepeat }: { task: Task; state: Scenario; onBack: () => void; onProfile: (candidateId: string) => void; onMessages: (candidateId: string) => void; onApplications: () => void; onResults: () => void; onRepeat: () => void }) {
  const assigned = state.applications.filter((item) => item.taskId === task.id && item.status === "assigned");
  const invited = state.taskInvitations?.filter((item) => item.taskId === task.id) ?? [];
  const result = state.results.find((item) => item.taskId === task.id);
  return <div className="feature-stack task-detail-page customer-task-detail">
    <button className="text-button" type="button" onClick={onBack}>← Вернуться к моим задачам</button>
    <header className="task-detail-hero"><div><p className="eyebrow">Задача заказчика · {task.id}</p><h1>{task.title}</h1><p className="lead">{task.problem}</p><div className="work-meta"><span className="ui-badge ui-badge--info">{status[task.status]}</span><span>{task.direction}</span><span>Срок {task.deadline}</span></div></div><aside className="customer-task-terms"><small>Условия задачи</small><strong>Версия {task.version}</strong><p>{task.mode === "invitation_only" ? "Доступ по приглашению" : "Открытый отклик"}</p><p>{task.places} мест · {task.department}</p><button type="button" onClick={onRepeat}>Повторить задачу</button></aside></header>
    <section className="task-people-grid"><article><span className="eyebrow">В работе</span><strong>{assigned.length} участников</strong><small>Назначены на задачу</small></article><article><span className="eyebrow">Заявки</span><strong>{state.applications.filter((item) => item.taskId === task.id).length}</strong><small>Можно открыть и отобрать</small><button className="text-button" type="button" onClick={onApplications}>Посмотреть заявки</button></article><article><span className="eyebrow">Результат</span><strong>{result ? result.status === "accepted" ? "Принят" : "Получен" : "Пока нет"}</strong><small>{result?.summary ?? "Ожидается от исполнителей"}</small>{result && <button className="text-button" type="button" onClick={onResults}>Открыть приёмку</button>}</article></section>
    <div className="task-detail-grid"><section className="task-work-plan"><div className="section-heading"><div><p className="eyebrow">Постановка</p><h2>Бриф и критерии</h2></div></div><article className="customer-detail-block"><small>Проблема и цель</small><p>{task.problem}</p></article><article className="customer-detail-block"><small>Ожидаемый результат</small><p>{task.deliverable}</p></article><article className="customer-detail-block"><small>Критерии успешности</small><p>{task.criteria}</p></article><article className="customer-detail-block"><small>Ход работы</small><p>{task.status === "draft" ? "Черновик готовится к публикации" : task.status === "published" ? "Сбор заявок и приглашений" : task.status === "in_progress" ? "Участники выполняют задачу" : task.status === "review" ? "Результат ожидает приёмки" : "Результат принят"}</p></article></section>
      <aside className="task-team-panel"><h2>Исполнители и менторы</h2>{assigned.length ? <ul>{assigned.map((item) => { const person = state.candidates.find((candidate) => candidate.id === item.candidateId); return <li key={item.candidateId}><span>{person?.name.split(" ").map((part) => part[0]).join("") ?? "У"}</span><div><button className="customer-person-link" type="button" onClick={() => { onProfile(item.candidateId); }}>{person?.name ?? "Участник"}</button><small>{person?.direction ?? "Направление не указано"}</small><small>Ментор: {person?.mentor ?? "Не назначен"}</small><button className="text-button" type="button" onClick={() => { onMessages(item.candidateId); }}>Написать лично</button></div></li>; })}</ul> : <p>Исполнители ещё не назначены.</p>}{invited.length > 0 && <p>Ожидают ответа на приглашение: {invited.map((item) => name(state, item.candidateId)).join(", ")}</p>}</aside></div>
  </div>;
}

function CustomerCandidateProfile({ person, task, onBack, onMessage }: { person: Candidate; task: Task; onBack: () => void; onMessage: () => void }) {
  const skills = [...new Set(person.cases.flatMap((item) => item.skills))];
  const rubric = person.cases.find((item) => item.rubric)?.rubric ?? {};
  return <div className="feature-stack customer-talent-profile">
    <button className="text-button" type="button" onClick={onBack}>← Вернуться к задаче</button>
    <header className="portfolio-profile-card"><div className="portfolio-identity"><span className="portfolio-avatar" aria-hidden="true">{person.name.split(" ").map((part) => part[0]).join("")}</span><div><p className="eyebrow">Цифровой профиль компетенций</p><h1>{person.name}</h1><p>{person.direction} · {person.education ?? "Образование не указано"}</p><small>{person.city ?? "Город не указан"} · Ментор {person.mentor ?? "не назначен"}</small></div></div><div className="portfolio-profile-actions"><button type="button" onClick={onMessage}>Написать лично</button></div><div className="portfolio-kpis"><div><span>Принятые кейсы</span><strong>{person.cases.length}</strong></div><div><span>Подтверждённые навыки</span><strong>{skills.length}</strong></div><div><span>Экспертные оценки</span><strong>{person.cases.filter((item) => item.expert).length}</strong></div><div><span>Направление задачи</span><strong className="customer-match-text">{person.direction === task.direction ? "Совпадает" : "Другое"}</strong></div></div><div className="portfolio-skills"><strong>Подтверждено практикой</strong><div>{skills.map((skill) => <span key={skill}>✓ {skill}</span>)}</div></div></header>
    <div className="customer-profile-grid"><section className="task-work-plan"><div className="section-heading"><div><p className="eyebrow">Evidence first</p><h2>Подтверждённые кейсы</h2></div></div>{person.cases.map((item) => <article className="customer-detail-block" key={item.title}><h3>{item.title}</h3><p>{item.artifact}</p><small>Проверил: {item.expert ?? "эксперт"} · {item.completedAt ?? "дата не указана"}</small><p>Навыки: {item.skills.join(", ")}</p></article>)}</section><aside className="task-team-panel"><h2>Аналитика решений</h2><p>Оценка по критериям завершённого кейса</p>{Object.entries(rubric).map(([label, value]) => <div className="customer-skill-row" key={label}><div><span>{label}</span><strong>{value}%</strong></div><meter min="0" max="100" value={value}>{value}%</meter></div>)}<h3>Обучение</h3><p>{person.courses?.join(" · ") ?? "Курсы не указаны"}</p><small>Факт обучения показан отдельно от подтверждённых практикой навыков.</small></aside></div>
  </div>;
}

function CandidatePicker({ candidates, direction, selected, onChange }: { candidates: Candidate[]; direction: string; selected: string[]; onChange: (ids: string[]) => void }) {
  const eligible = candidates.filter((person) => person.cases.length > 0);
  return <fieldset className="customer-candidate-picker"><legend>Участники для адресного приглашения</legend><p>Можно выбрать исполнителей с уже принятыми кейсами. После публикации им потребуется принять приглашение.</p>{eligible.map((person) => <label key={person.id}><input type="checkbox" checked={selected.includes(person.id)} onChange={() => { onChange(selected.includes(person.id) ? selected.filter((id) => id !== person.id) : [...selected, person.id]); }} /><span><strong>{person.name}</strong><small>{person.direction === direction ? "Направление совпадает" : person.direction} · {person.cases[0]?.title}</small></span></label>)}</fieldset>;
}

export function CustomerScenario({ section }: { section: string }) {
  const navigate = useNavigate();
  const [searchParams] = useSearchParams();
  const taskParam = searchParams.get("task");
  const participantParam = searchParams.get("participant");
  const [state, setState] = useState<Scenario>(initial);
  const [page, setPage] = useState<Page>(section === "Мои задачи" && participantParam ? "Профиль" : section === "Мои задачи" && taskParam ? "Задача" : pages.includes(section as Section) ? section as Section : "Главная");
  const [selected, setSelected] = useState(taskParam ?? "IMP-101");
  const [selectedPerson, setSelectedPerson] = useState(participantParam ?? "p1");
  const [chatPerson, setChatPerson] = useState(participantParam ?? "p1");
  const [chosenCandidates, setChosenCandidates] = useState<string[]>([]);
  const [filter, setFilter] = useState("Все");
  const [step, setStep] = useState(0);
  const [brief, setBrief] = useState({ title: "", department: "Розничный бизнес", direction: "Аналитика данных", taskType: "MVP", problem: "", deliverable: "", criteria: "", deadline: later(28), places: 2, mode: "open" as Task["mode"], reward: "80000", dataTerms: "Открытые или обезличенные данные", ipTerms: "Результат передаётся заказчику", support: "Ментор и еженедельный review" });
  const [comment, setComment] = useState("");
  const [draftMessage, setDraftMessage] = useState("");
  const [assistantText, setAssistantText] = useState("");
  const [notice, setNotice] = useState("");
  const go = (target: Section) => { setPage(target); void navigate(`/workspace/${String(pages.indexOf(target))}`); };
  const openTask = (id: string) => { setSelected(id); setPage("Задача"); void navigate(`/workspace/1?task=${encodeURIComponent(id)}`); };
  const openProfile = (id: string) => { setSelectedPerson(id); setPage("Профиль"); void navigate(`/workspace/1?task=${encodeURIComponent(selected)}&participant=${encodeURIComponent(id)}`); };
  const openMessages = (id: string) => { setChatPerson(id); setPage("Сообщения"); void navigate(`/workspace/8?task=${encodeURIComponent(selected)}&participant=${encodeURIComponent(id)}`); };
  useEffect(() => { localStorage.setItem(key, JSON.stringify(state)); }, [state]);
  useEffect(() => { if (taskParam) setSelected(taskParam); if (participantParam) { setSelectedPerson(participantParam); setChatPerson(participantParam); } if (section === "Мои задачи" && participantParam) setPage("Профиль"); else if (section === "Мои задачи" && taskParam) setPage("Задача"); else if (pages.includes(section as Section)) setPage(section as Section); }, [section, taskParam, participantParam]);
  const task: Task = state.tasks.find((item) => item.id === selected) ?? state.tasks[0] ?? { id: "", title: "Задача", department: "", direction: "", problem: "", deliverable: "", criteria: "", deadline: "", status: "draft", mode: "open", places: 1, version: 1 };
  const pending = state.results.filter((item) => item.status === "submitted");
  const accepted = state.results.filter((item) => item.status === "accepted");
  const updateApplication = (candidateId: string, next: Application["status"]) => {
    setState((current) => ({ ...current, applications: current.applications.map((item) => item.taskId === selected && item.candidateId === candidateId ? { ...item, status: next } : item), tasks: next === "assigned" ? current.tasks.map((item) => item.id === selected ? { ...item, status: "in_progress" } : item) : current.tasks }));
  };
  const decide = (next: Result["status"]) => {
    const resultId = currentResult?.taskId ?? selected;
    setState((current) => ({ ...current, results: current.results.map((item) => item.taskId === resultId ? { ...item, status: next, comment } : item), tasks: current.tasks.map((item) => item.id === resultId ? { ...item, status: next === "accepted" ? "completed" : "in_progress" } : item) }));
    setNotice(next === "accepted" ? "Результат принят" : next === "revision" ? "Результат возвращён на доработку" : "Спор открыт");
  };
  const saveTask = (publish: boolean) => {
    if (!brief.title.trim() || !brief.problem.trim() || !brief.deliverable.trim() || !brief.criteria.trim()) { setNotice("Заполните название, проблему, результат и критерии"); return; }
    if (publish && brief.mode === "invitation_only" && chosenCandidates.length === 0) { setNotice("Для задачи по приглашению выберите хотя бы одного участника с подтверждённым кейсом"); return; }
    const created: Task = { ...brief, id: `IMP-${String(Date.now())}`, status: publish ? "published" : "draft", version: 1 };
    setState((current) => ({ ...current, tasks: [created, ...current.tasks], taskInvitations: publish ? [...(current.taskInvitations ?? []), ...chosenCandidates.map((candidateId) => ({ taskId: created.id, candidateId }))] : current.taskInvitations }));
    setSelected(created.id); setChosenCandidates([]); openTask(created.id); setNotice(publish ? chosenCandidates.length ? "Задача опубликована, адресные приглашения отправлены" : "Задача опубликована" : "Черновик сохранён");
  };
  const repeat = () => { const copy: Task = { ...task, id: `IMP-${String(Date.now())}`, title: `${task.title} — новый набор`, status: "draft", version: 1 }; setState((current) => ({ ...current, tasks: [copy, ...current.tasks] })); setSelected(copy.id); setNotice("Создан черновик на основе задачи"); };
  const currentResult = state.results.find((item) => item.taskId === selected) ?? pending[0];
  return <main className={`feature-stack customer-scenario customer-page-${String(pages.indexOf(page as Section))}`}>
    {page !== "Задача" && page !== "Профиль" && <header className="participant-page-heading"><div><p className="eyebrow">Рабочее пространство заказчика</p><h1>{page}</h1><p className="lead">Задачи, подтверждённый опыт участников и результаты в одном контуре.</p></div>{page === "Мои задачи" && <button type="button" onClick={() => { go("Создать задачу"); }}>Создать задачу</button>}</header>}
    {notice && <p role="status">{notice}</p>}
    {page === "Главная" && <><div className="customer-kpi-grid">{[["Опубликовано", state.tasks.filter((item) => item.status !== "draft").length], ["В работе", state.tasks.filter((item) => item.status === "in_progress").length], ["На проверке", pending.length], ["Принято", accepted.length]].map(([label, value]) => <article className="compact-panel" key={label}><small>{label}</small><h2>{value}</h2></article>)}</div><section className="compact-panel"><p className="eyebrow">Ближайшая задача под контролем</p><h2>{(pending.length ? state.tasks.find((item) => item.id === pending[0]?.taskId) : task)?.title}</h2><p>{pending.length ? "Поступил результат, требуется решение заказчика" : `${status[task.status]} · срок ${task.deadline}`}</p><button type="button" onClick={() => { setSelected(pending[0]?.taskId ?? task.id); go(pending.length ? "Приёмка" : "Мои задачи"); }}>Открыть задачу</button></section><section className="compact-panel"><h2>Последние результаты</h2>{state.results.length ? state.results.map((item) => <p key={`${item.taskId}-${item.candidateId}`}>{name(state, item.candidateId)} · {state.tasks.find((candidate) => candidate.id === item.taskId)?.title} · {item.status === "accepted" ? "Принят" : item.status === "submitted" ? "На проверке" : item.status === "revision" ? "Доработка" : "Спор"}</p>) : <p>Результаты ещё не поступили</p>}</section><button type="button" onClick={() => { go("AI-помощник"); }}>Уточнить бриф с AI-помощником</button></>}
    {page === pages[1] && <CustomerTaskList state={state} filter={filter} onFilter={setFilter} onOpen={openTask} />}
    {page === "Задача" && <CustomerTaskDetail task={task} state={state} onBack={() => { go("Мои задачи"); }} onProfile={openProfile} onMessages={openMessages} onApplications={() => { go("Заявки"); }} onResults={() => { go("Приёмка"); }} onRepeat={repeat} />}
    {page === "Профиль" && state.candidates.find((item) => item.id === selectedPerson) && <CustomerCandidateProfile person={state.candidates.find((item) => item.id === selectedPerson) ?? state.candidates[0] as Candidate} task={task} onBack={() => { openTask(task.id); }} onMessage={() => { openMessages(selectedPerson); }} />}
    {page === "Создать задачу" && <div className="create-task-workspace">
      <ol className="create-stepper">{["Бриф","Критерии и сроки","Формат и данные","Поддержка","Проверка и публикация"].map((label,index)=><li className={index<step?"done":index===step?"active":""} key={label}><span>{index<step?"✓":index+1}</span><b>{label}</b></li>)}</ol>
      <div className="create-task-grid"><section className="create-form-card"><p className="eyebrow">Шаг {step+1} из 5</p><h2>{["Опишите задачу","Зафиксируйте измеримые критерии","Определите условия","Настройте поддержку","Проверьте перед публикацией"][step]}</h2>
        {step===0&&<div className="create-fields"><label className="wide">Название задачи<input value={brief.title} onChange={event=>{setBrief({...brief,title:event.target.value});}} placeholder="Например, MVP рекомендательной системы"/></label><div className="task-type-picker">{["R&D","MVP","Исследование"].map(type=><button className={brief.taskType===type?"active":""} type="button" key={type} onClick={()=>{setBrief({...brief,taskType:type});}}><b>{type}</b><small>{type==="MVP"?"Рабочий прототип":type==="R&D"?"Проверка гипотезы":"Анализ подходов"}</small></button>)}</div><label>Подразделение<select value={brief.department} onChange={event=>{setBrief({...brief,department:event.target.value});}}>{["Розничный бизнес","Клиентский сервис","R&D"].map(item=><option key={item}>{item}</option>)}</select></label><label>Направление<select value={brief.direction} onChange={event=>{setBrief({...brief,direction:event.target.value});}}>{["Аналитика данных","AI / ML","NLP","Computer Vision"].map(item=><option key={item}>{item}</option>)}</select></label><label className="wide">Проблема и цель<textarea value={brief.problem} onChange={event=>{setBrief({...brief,problem:event.target.value});}} placeholder="Какую реальную проблему нужно решить и почему она важна?"/></label><label className="wide">Ожидаемый результат<textarea value={brief.deliverable} onChange={event=>{setBrief({...brief,deliverable:event.target.value});}} placeholder="Прототип, API, отчёт, презентация и другие артефакты"/></label></div>}
        {step===1&&<div className="create-fields"><label className="wide">Критерии успеха<textarea value={brief.criteria} onChange={event=>{setBrief({...brief,criteria:event.target.value});}} placeholder="Метрики качества, воспроизводимость, документация"/></label><label>Дедлайн<input type="date" value={brief.deadline} onChange={event=>{setBrief({...brief,deadline:event.target.value});}}/></label><label>Количество мест<input type="number" min="1" value={brief.places} onChange={event=>{setBrief({...brief,places:Number(event.target.value)});}}/></label></div>}
        {step===2&&<div className="create-fields"><div className="task-type-picker wide">{[["open","Открытая задача"],["invitation_only","По приглашению"]].map(([value,label])=><button className={brief.mode===value?"active":""} type="button" key={value} onClick={()=>{setBrief({...brief,mode:value as Task["mode"]});}}><b>{label}</b><small>{value==="open"?"Заявки доступны всем подходящим участникам":"Только выбранные кандидаты"}</small></button>)}</div><label className="wide">Данные<input value={brief.dataTerms} onChange={event=>{setBrief({...brief,dataTerms:event.target.value});}}/></label><label className="wide">Права на результат<textarea value={brief.ipTerms} onChange={event=>{setBrief({...brief,ipTerms:event.target.value});}}/></label></div>}
        {step===3&&<div className="create-fields"><label className="wide">Модель поддержки<textarea value={brief.support} onChange={event=>{setBrief({...brief,support:event.target.value});}}/></label><CandidatePicker candidates={state.candidates} direction={brief.direction} selected={chosenCandidates} onChange={setChosenCandidates}/></div>}
        {step===4&&<div className="create-summary"><div><small>Название</small><b>{brief.title||"Не заполнено"}</b></div><div><small>Тип и направление</small><b>{brief.taskType} · {brief.direction}</b></div><div><small>Ожидаемый результат</small><b>{brief.deliverable||"Не заполнено"}</b></div><div><small>Критерии</small><b>{brief.criteria||"Не заполнено"}</b></div><div><small>Условия</small><b>{brief.mode==="open"?"Открытая":"По приглашению"} · {brief.deadline}</b></div></div>}
      </section><aside className="create-ai-panel"><span className="ai-orb">✧</span><p className="eyebrow">AI-помощник</p><h2>Как усилить постановку</h2>{["Добавьте целевую аудиторию решения","Укажите формат и источник данных","Зафиксируйте порог качества","Опишите сценарий демонстрации"].slice(0,step+2).map(tip=><article key={tip}><b>{tip}</b><button type="button" onClick={()=>{setNotice(`Рекомендация применена: ${tip}`);}}>Применить</button></article>)}<small>AI помогает сформулировать задачу. Публикацию и условия подтверждает заказчик.</small></aside></div>
      <footer className="create-actions"><button type="button" disabled={step===0} onClick={()=>{setStep(step-1);}}>Назад</button><button type="button" onClick={()=>{saveTask(false);}}>Сохранить черновик</button><button type="button" onClick={()=>{setNotice(`Предпросмотр: ${brief.title||"Без названия"} · ${brief.deliverable||"Результат не указан"}`);}}>Предпросмотр</button>{step<4?<button className="primary" type="button" onClick={()=>{setStep(step+1);}}>Продолжить</button>:<button className="primary" type="button" onClick={()=>{saveTask(true);}}>Опубликовать</button>}</footer>
    </div>}
    {page === "Заявки" && <section className="compact-panel"><h2>Заявки на {task.title}</h2><p>Всего {state.applications.filter((item) => item.taskId === selected).length} · шорт-лист {state.applications.filter((item) => item.taskId === selected && item.status === "shortlisted").length} · назначено {state.applications.filter((item) => item.taskId === selected && item.status === "assigned").length}</p>{state.applications.filter((item) => item.taskId === selected).map((item) => { const person = state.candidates.find((candidate) => candidate.id === item.candidateId); return <article key={item.candidateId} style={{ borderTop: "1px solid #ddd", padding: 12 }}><h3>{person?.name}</h3><p>{person?.direction} · {person?.cases.map((entry) => `${entry.title}: ${entry.artifact}`).join("; ")}</p><p>Статус: {item.status}</p><div style={{ display: "flex", gap: 8 }}><button type="button" onClick={() => { updateApplication(item.candidateId, "shortlisted"); }}>В шорт-лист</button><button type="button" onClick={() => { updateApplication(item.candidateId, "waitlisted"); }}>Лист ожидания</button><button type="button" onClick={() => { updateApplication(item.candidateId, "assigned"); }}>Назначить</button></div></article>; })}{!state.applications.some((item) => item.taskId === selected) && <p>Заявок пока нет</p>}</section>}
    {page === "Приёмка" && <><div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>{state.results.map((item) => <button type="button" key={item.taskId} onClick={() => { setSelected(item.taskId); }}>{state.tasks.find((entry) => entry.id === item.taskId)?.title}</button>)}</div><section className="compact-panel"><p>Бриф → Работа → Сдача → Ревью → Приёмка</p><h2>{state.tasks.find((item) => item.id === currentResult?.taskId)?.title ?? task.title}</h2>{currentResult ? <><p>Участник: {name(state, currentResult.candidateId)}</p><p>{currentResult.summary}</p><p>Артефакты: {currentResult.artifact}</p><p>Условия версии {state.tasks.find((item) => item.id === currentResult.taskId)?.version}: {state.tasks.find((item) => item.id === currentResult.taskId)?.criteria}</p><label><input type="checkbox" /> Артефакты соответствуют ожидаемому результату</label><p>Текущее решение: {currentResult.status}</p><label>Комментарий <textarea value={comment} onChange={(event) => { setComment(event.target.value); }} /></label><div style={{ display: "flex", gap: 8 }}><button type="button" onClick={() => { setSelected(currentResult.taskId); decide("accepted"); }}>Принять</button><button type="button" onClick={() => { setSelected(currentResult.taskId); decide("revision"); }}>Вернуть на доработку</button><button type="button" onClick={() => { setSelected(currentResult.taskId); decide("disputed"); }}>Открыть спор</button></div></> : <p>Результатов пока нет</p>}</section></>}
    {page === "Аналитика" && <><div className="customer-kpi-grid">{[["Задач", state.tasks.filter((item) => item.status !== "draft").length], ["С заявками", new Set(state.applications.map((item) => item.taskId)).size], ["С результатом", new Set(state.results.map((item) => item.taskId)).size], ["Принято", accepted.length]].map(([label, value]) => <article className="compact-panel" key={label}><small>{label}</small><h2>{value}</h2></article>)}</div><section className="compact-panel"><h2>Воронка задач</h2><p>Опубликовано → Есть заявки → Назначены участники → Есть результаты → Приняты результаты</p><p>{state.tasks.filter((item) => item.status !== "draft").length} → {new Set(state.applications.map((item) => item.taskId)).size} → {new Set(state.applications.filter((item) => item.status === "assigned").map((item) => item.taskId)).size} → {new Set(state.results.map((item) => item.taskId)).size} → {accepted.length}</p><p>Время до результата: появится после фиксации дат. Экономия времени отбора: нет базы для сравнения.</p><p>Направления: Аналитика данных · AI / ML. Подразделения: Розничный бизнес · Клиентский сервис · R&D.</p></section></>}
    {page === "AI-помощник" && <section className="compact-panel"><h2>Помощь с задачей</h2><p>Подсказки требуют проверки заказчиком. Публикация и приёмка остаются его решениями.</p><div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>{["Уточнить бриф", "Предложить критерии", "Оценить риски", "Разобрать отклики"].map((item) => <button type="button" key={item} onClick={() => { setAssistantText(item === "Уточнить бриф" ? `Проблема: ${task.problem}. Уточните исходные данные, ограничения и целевую аудиторию.` : item === "Предложить критерии" ? `Проверьте измеримые метрики: ${task.criteria}. Добавьте порог качества и формат воспроизведения.` : item === "Оценить риски" ? "Проверьте доступность данных, качество разметки, вычислительные ограничения и права на результат." : `По задаче ${task.title} поступило ${String(state.applications.filter((entry) => entry.taskId === selected).length)} заявок. Сравните подтверждённые кейсы и доступность.`); }}>{item}</button>)}</div><textarea aria-label="Рекомендация помощника" placeholder="Выберите один из сценариев выше — рекомендацию можно отредактировать перед использованием." value={assistantText} onChange={(event) => { setAssistantText(event.target.value); }} style={{ width: "100%", minHeight: 130 }} /><p>Контекст: {task.title} · {status[task.status]} · дедлайн {task.deadline}</p><button type="button" onClick={() => { setAssistantText(""); }}>Очистить</button></section>}
    {page === "Кандидаты" && <section className="compact-panel"><h2>Участники с подтверждёнными кейсами</h2><p>Всего {state.candidates.length} · сохранено {state.saved.length} · приглашено {state.invited.length}</p>{state.candidates.map((person) => <article key={person.id} style={{ borderTop: "1px solid #ddd", padding: 12 }}><h3>{person.name}</h3><p>{person.direction} · {person.cases.flatMap((item) => item.skills).join(", ")}</p>{person.cases.map((item) => <p key={item.title}><strong>{item.title}</strong> · {item.artifact}</p>)}<div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}><button type="button" onClick={() => { setState((current) => ({ ...current, saved: current.saved.includes(person.id) ? current.saved.filter((id) => id !== person.id) : [...current.saved, person.id] })); }}>{state.saved.includes(person.id) ? "Убрать из резерва" : "Сохранить в резерв"}</button><button type="button" onClick={() => { setState((current) => ({ ...current, invited: current.invited.includes(person.id) ? current.invited : [...current.invited, person.id] })); }}>Пригласить в задачу</button><button type="button" onClick={() => { setState((current) => ({ ...current, interviews: current.interviews.includes(person.id) ? current.interviews : [...current.interviews, person.id] })); }}>Отметить интерес к интервью</button></div><small>{state.invited.includes(person.id) ? "Приглашён · " : ""}{state.interviews.includes(person.id) ? "Интерес к интервью отмечен" : ""}</small></article>)}</section>}
    {page === pages[8] && <section className="task-marketplace customer-messages"><div className="section-heading"><div><p className="eyebrow">Личная переписка</p><h2>{name(state, chatPerson)}</h2></div></div><p>Задача: {task.title} ? срок {task.deadline}</p><label>Участник<select value={chatPerson} onChange={(event) => { setChatPerson(event.target.value); }}>{state.candidates.map((person) => <option key={person.id} value={person.id}>{person.name}</option>)}</select></label><div className="customer-message-history">{state.messages.filter((item) => item.taskId === selected && item.candidateId === chatPerson).map((item, index) => <p key={`${item.author}-${String(index)}`}><strong>{item.author}:</strong> {item.body}</p>)}</div><label>Сообщение<textarea value={draftMessage} onChange={(event) => { setDraftMessage(event.target.value); }} /></label><button type="button" onClick={() => { if (!draftMessage.trim()) return; setState((current) => ({ ...current, messages: [...current.messages, { taskId: selected, candidateId: chatPerson, author: "Заказчик", body: draftMessage.trim() }] })); setDraftMessage(""); }}>Отправить</button></section>}
  </main>;
}
