import { SkillMatchWheel } from "../components/skill-match-wheel";

const criteria=[
  ["Системное мышление",82],["Технические навыки",91],["Решение задач",89],
  ["Работа в команде",84],["Коммуникация",78],["Работа с данными",86],
] as const;

export function CustomerAnalytics() {
  return <div className="feature-stack participant-analytics analytics-dashboard"><header className="participant-page-heading"><div><p className="eyebrow">Подтверждённый потенциал</p><h1 id="workspace-title">Аналитика кандидатов</h1><p className="lead">Сравнивайте соответствие задаче по результатам реальных кейсов и экспертной оценки.</p></div><select aria-label="Выбранная задача"><option>Рекомендательная система</option><option>Аналитика документов</option></select></header><section className="metric-grid participant-kpi-grid"><article className="metric-card metric-card--teal"><span>Средний match</span><strong>87%</strong><small>+6% за месяц</small></article><article className="metric-card metric-card--blue"><span>Подходящие кандидаты</span><strong>48</strong><small>12 доступны сейчас</small></article><article className="metric-card metric-card--violet"><span>Подтверждённые кейсы</span><strong>126</strong><small>по выбранному направлению</small></article><article className="metric-card metric-card--teal"><span>Приглашено</span><strong>14</strong><small>7 приняли приглашение</small></article></section><div className="customer-candidate-analytics"><section><h2>Совпадение с задачей</h2><SkillMatchWheel/></section><section className="analytics-criteria"><h2>Критерии оценки</h2><p>Оценка строится по уже завершённым конкретным кейсам.</p>{criteria.map(([label,value])=><div key={label}><span>{label}</span><strong>{value}%</strong><i><b style={{width:`${String(value)}%`}}/></i></div>)}</section></div><section className="analytics-dashboard-card"><div className="section-heading"><div><p className="eyebrow">Динамика</p><h2>Качество talent pipeline</h2></div></div><div className="customer-histogram" role="img" aria-label="Гистограмма качества кандидатов">{[48,64,57,72,68,83,79,91].map((value,index)=><span key={String(index)}><i style={{height:`${String(value)}%`}}/><small>{index+1} нед.</small></span>)}</div></section></div>;
}
