import { useState, type SyntheticEvent } from "react";
import { Badge } from "../components/ui";

export function CustomerAssistant() {
  const actions=["Сформулировать бриф","Уточнить критерии","Проверить задачу","Разобрать отклики","Оценить риски"];
  const [value,setValue]=useState("");
  const [messages,setMessages]=useState([{from:"buddy",text:"Вижу текущую задачу и 28 заявок. Могу улучшить бриф, предложить измеримые критерии или сравнить подтверждённые кейсы кандидатов."}]);
  const send=(event:SyntheticEvent<HTMLFormElement>)=>{event.preventDefault();const text=value.trim();if(!text)return;setMessages(items=>[...items,{from:"user",text},{from:"buddy",text:"Подготовил рекомендацию по задаче: уточните исходные данные, порог качества и обязательные артефакты. Решение о публикации и выборе участника остаётся за вами."}]);setValue("");};
  return <div className="buddy-page feature-stack"><header className="participant-page-heading"><div><p className="eyebrow">Интеллектуальный помощник</p><h1 id="workspace-title">AI-помощник</h1><p className="lead">Помогает улучшать постановку задач, критерии и разбор откликов.</p></div><Badge tone="warning">Бета · AI</Badge></header><div className="buddy-layout"><main className="buddy-chat"><div className="quick-prompts">{actions.map(action=><button type="button" key={action} onClick={()=>{setValue(action);}}>{action}</button>)}</div><div className="buddy-messages">{messages.map((message,index)=><article className={`buddy-message buddy-message--${message.from}`} key={`${message.from}-${String(index)}`}><span>{message.from==="buddy"?"✧":"Вы"}</span><p>{message.text}</p></article>)}</div><form onSubmit={send}><input aria-label="Сообщение AI-помощнику" value={value} onChange={event=>{setValue(event.target.value);}} placeholder="Спросите о задаче, критериях или кандидатах…"/><button type="submit">Отправить</button></form></main><aside className="buddy-context"><p className="eyebrow">Контекст задачи</p><h2>Рекомендательная система</h2><article><Badge tone="warning">R&D · В работе</Badge><strong>28 заявок · 3 исполнителя</strong><small>Дедлайн 25 апреля 2025</small><button type="button" onClick={()=>{window.location.assign("/workspace/1");}}>Открыть задачу →</button></article><h3>На чём основан совет</h3><ul><li>Зафиксированная версия брифа</li><li>Критерии результата</li><li>Подтверждённые кейсы кандидатов</li><li>История похожих задач</li></ul><button className="secondary-button" type="button" onClick={()=>{window.location.assign("/workspace/8");}}>Передать оператору</button><small>Окончательные решения принимает заказчик.</small></aside></div></div>;
}
