import { useEffect, useState } from "react";

type Page = "Главная" | "Мои задачи" | "Создать задачу" | "Заявки" | "Приёмка" | "Аналитика" | "AI-помощник" | "Кандидаты" | "Сообщения";
type Task = { id: string; title: string; department: string; direction: string; problem: string; deliverable: string; criteria: string; deadline: string; status: "draft" | "published" | "in_progress" | "review" | "completed"; mode: "open" | "invitation_only"; places: number; version: number };
type Application = { taskId: string; candidateId: string; status: "applied" | "shortlisted" | "waitlisted" | "assigned" };
type Result = { taskId: string; candidateId: string; summary: string; artifact: string; status: "submitted" | "accepted" | "revision" | "disputed"; comment: string };
type Candidate = { id: string; name: string; direction: string; cases: { title: string; artifact: string; skills: string[] }[] };
type Message = { taskId: string; author: string; body: string };
type Scenario = { tasks: Task[]; applications: Application[]; results: Result[]; candidates: Candidate[]; saved: string[]; invited: string[]; interviews: string[]; messages: Message[] };
const pages: Page[] = ["Главная", "Мои задачи", "Создать задачу", "Заявки", "Приёмка", "Аналитика", "AI-помощник", "Кандидаты", "Сообщения"];
const today = new Date();
const later = (days: number) => new Date(today.getTime() + days * 86400000).toISOString().slice(0, 10);
const seed: Scenario = {
  tasks: [
    { id: "IMP-101", title: "Прогноз загрузки отделений", department: "Розничный бизнес", direction: "Аналитика данных", problem: "Спрогнозировать нагрузку на отделения по обезличенным историческим данным", deliverable: "Отчёт, воспроизводимый ноутбук и презентация", criteria: "Качество прогноза, воспроизводимость и объяснение ошибок", deadline: later(21), status: "review", mode: "open", places: 2, version: 1 },
    { id: "IMP-102", title: "Классификация обращений", department: "Клиентский сервис", direction: "AI / ML", problem: "Сократить время маршрутизации обращений", deliverable: "Прототип классификатора, демо и инструкция", criteria: "Macro F1, задержка ответа и анализ неоднозначных случаев", deadline: later(36), status: "in_progress", mode: "open", places: 2, version: 1 },
    { id: "IMP-103", title: "Анализ качества поисковой выдачи", department: "R&D", direction: "Аналитика данных", problem: "Найти причины нерелевантных ответов внутреннего поиска", deliverable: "Исследование, метрики и рекомендации", criteria: "Обоснованность выборки и проверяемость выводов", deadline: later(50), status: "published", mode: "open", places: 3, version: 1 },
    { id: "IMP-104", title: "Исследование прогноза спроса", department: "Розничный бизнес", direction: "Аналитика данных", problem: "Проверить гипотезы о сезонности спроса", deliverable: "Исследование с воспроизводимыми расчётами", criteria: "Воспроизводимость и обоснованность прогноза", deadline: later(60), status: "published", mode: "invitation_only", places: 2, version: 1 },
  ],
  candidates: [
    { id: "p1", name: "Мария Ковалёва", direction: "Аналитика данных", cases: [{ title: "Прогноз загрузки отделений", artifact: "Отчёт и ноутбук · принят заказчиком", skills: ["Python", "прогнозирование", "защита решения"] }] },
    { id: "p2", name: "Иван Петров", direction: "AI / ML", cases: [{ title: "Классификация обращений", artifact: "Прототип и разбор ошибок · принят заказчиком", skills: ["NLP", "оценка модели", "работа с неопределённостью"] }] },
    { id: "p3", name: "Алина Сергеева", direction: "Аналитика данных", cases: [{ title: "Исследование клиентского пути", artifact: "Отчёт и презентация · приняты заказчиком", skills: ["SQL", "аналитика", "аргументация"] }] },
  ],
  applications: [{ taskId: "IMP-101", candidateId: "p1", status: "assigned" }, { taskId: "IMP-102", candidateId: "p2", status: "assigned" }, { taskId: "IMP-103", candidateId: "p3", status: "applied" }],
  results: [{ taskId: "IMP-101", candidateId: "p1", summary: "Модель прогноза и анализ ошибок по сегментам", artifact: "Отчёт · ноутбук · презентация", status: "submitted", comment: "" }],
  saved: [], invited: [], interviews: [], messages: [{ taskId: "IMP-101", author: "Мария Ковалёва", body: "Отправила отчёт и воспроизводимый ноутбук на проверку." }],
};
const key = "impulse-customer-pilot-v1";
function initial(): Scenario { try { const value = localStorage.getItem(key); return value ? JSON.parse(value) as Scenario : seed; } catch { return seed; } }
const status = { draft: "Черновик", published: "Опубликована", in_progress: "В работе", review: "На проверке", completed: "Завершена" };
const name = (state: Scenario, id: string) => state.candidates.find((person) => person.id === id)?.name ?? "Участник";

export function CustomerScenario({ section }: { section: string }) {
  const [state, setState] = useState<Scenario>(initial);
  const [page, setPage] = useState<Page>(pages.includes(section as Page) ? section as Page : "Главная");
  const [selected, setSelected] = useState("IMP-101");
  const [filter, setFilter] = useState("Все");
  const [step, setStep] = useState(0);
  const [brief, setBrief] = useState({ title: "", department: "Розничный бизнес", direction: "Аналитика данных", problem: "", deliverable: "", criteria: "", deadline: later(28), places: 2, mode: "open" as Task["mode"] });
  const [comment, setComment] = useState("");
  const [draftMessage, setDraftMessage] = useState("");
  const [assistantText, setAssistantText] = useState("");
  const [notice, setNotice] = useState("");
  useEffect(() => { localStorage.setItem(key, JSON.stringify(state)); }, [state]);
  useEffect(() => { if (pages.includes(section as Page)) setPage(section as Page); }, [section]);
  const task: Task = state.tasks.find((item) => item.id === selected) ?? state.tasks[0] ?? { id: "", title: "Задача", department: "", direction: "", problem: "", deliverable: "", criteria: "", deadline: "", status: "draft", mode: "open", places: 1, version: 1 };
  const pending = state.results.filter((item) => item.status === "submitted");
  const accepted = state.results.filter((item) => item.status === "accepted");
  const updateApplication = (candidateId: string, next: Application["status"]) => {
    setState((current) => ({ ...current, applications: current.applications.map((item) => item.taskId === selected && item.candidateId === candidateId ? { ...item, status: next } : item), tasks: next === "assigned" ? current.tasks.map((item) => item.id === selected ? { ...item, status: "in_progress" } : item) : current.tasks }));
  };
  const decide = (next: Result["status"]) => {
    const resultId = currentResult?.taskId ?? selected;
    setState((current) => ({ ...current, results: current.results.map((item) => item.taskId === resultId ? { ...item, status: next, comment } : item), tasks: current.tasks.map((item) => item.id === resultId ? { ...item, status: next === "accepted" ? "completed" : "in_progress" } : item) }));
    setNotice(next === "accepted" ? "Результат принят" : next === "revision" ? "Результат возвращён на доработку" : "Спор открыт");
  };
  const saveTask = (publish: boolean) => {
    if (!brief.title.trim() || !brief.problem.trim() || !brief.deliverable.trim() || !brief.criteria.trim()) { setNotice("Заполните название, проблему, результат и критерии"); return; }
    const created: Task = { ...brief, id: `IMP-${String(Date.now())}`, status: publish ? "published" : "draft", version: 1 };
    setState((current) => ({ ...current, tasks: [created, ...current.tasks] })); setSelected(created.id); setPage("Мои задачи"); setNotice(publish ? "Задача опубликована" : "Черновик сохранён");
  };
  const repeat = () => { const copy: Task = { ...task, id: `IMP-${String(Date.now())}`, title: `${task.title} — новый набор`, status: "draft", version: 1 }; setState((current) => ({ ...current, tasks: [copy, ...current.tasks] })); setSelected(copy.id); setNotice("Создан черновик на основе задачи"); };
  const shownTasks = state.tasks.filter((item) => filter === "Все" || status[item.status] === filter);
  const currentResult = state.results.find((item) => item.taskId === selected) ?? pending[0];
  return <main className="customer-scenario" style={{ padding: "24px", display: "grid", gap: "20px" }}>
    <header><p className="eyebrow">Рабочее пространство заказчика</p><h1>{page}</h1><p>Задачи, подтверждённый опыт участников и результаты в одном контуре.</p></header>
    <nav aria-label="Разделы заказчика" style={{ display: "flex", flexWrap: "wrap", gap: "8px" }}>{pages.map((item) => <button key={item} type="button" className={page === item ? "primary-button" : "secondary-button"} onClick={() => { setPage(item); }}>{item}</button>)}</nav>
    {notice && <p role="status">{notice}</p>}
    {page === "Главная" && <><div className="customer-kpi-grid">{[["Опубликовано", state.tasks.filter((item) => item.status !== "draft").length], ["В работе", state.tasks.filter((item) => item.status === "in_progress").length], ["На проверке", pending.length], ["Принято", accepted.length]].map(([label, value]) => <article className="compact-panel" key={label}><small>{label}</small><h2>{value}</h2></article>)}</div><section className="compact-panel"><p className="eyebrow">Ближайшая задача под контролем</p><h2>{(pending.length ? state.tasks.find((item) => item.id === pending[0]?.taskId) : task)?.title}</h2><p>{pending.length ? "Поступил результат, требуется решение заказчика" : `${status[task.status]} · срок ${task.deadline}`}</p><button type="button" onClick={() => { setSelected(pending[0]?.taskId ?? task.id); setPage(pending.length ? "Приёмка" : "Мои задачи"); }}>Открыть задачу</button></section><section className="compact-panel"><h2>Последние результаты</h2>{state.results.length ? state.results.map((item) => <p key={`${item.taskId}-${item.candidateId}`}>{name(state, item.candidateId)} · {state.tasks.find((candidate) => candidate.id === item.taskId)?.title} · {item.status === "accepted" ? "Принят" : item.status === "submitted" ? "На проверке" : item.status === "revision" ? "Доработка" : "Спор"}</p>) : <p>Результаты ещё не поступили</p>}</section><button type="button" onClick={() => { setPage("AI-помощник"); }}>Уточнить бриф с AI-помощником</button></>}
    {page === "Мои задачи" && <><div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>{["Все", "Опубликована", "В работе", "На проверке", "Завершена", "Черновик"].map((item) => <button type="button" key={item} onClick={() => { setFilter(item); }} aria-pressed={filter === item}>{item}</button>)}</div><div className="customer-lower-grid"><section className="compact-panel"><h2>Портфель задач</h2>{shownTasks.map((item) => <button type="button" key={item.id} onClick={() => { setSelected(item.id); }} style={{ display: "block", width: "100%", textAlign: "left", marginBottom: 12 }}><strong>{item.title}</strong><br /><small>{item.department} · {status[item.status]} · заявок {state.applications.filter((entry) => entry.taskId === item.id).length} · срок {item.deadline}</small></button>)}</section><aside className="compact-panel"><h2>{task.title}</h2><p>{task.id} · версия условий {task.version} · {task.direction}</p><p><strong>Проблема:</strong> {task.problem}</p><p><strong>Результат:</strong> {task.deliverable}</p><p><strong>Критерии:</strong> {task.criteria}</p><p><strong>Формат:</strong> {task.mode === "open" ? "Открытая задача" : "По приглашению"}</p><p>Последний результат: {state.results.find((item) => item.taskId === task.id)?.summary ?? "Пока нет"}</p><div style={{ display: "flex", flexWrap: "wrap", gap: 8 }}><button type="button" onClick={() => { setPage("Заявки"); }}>Заявки</button><button type="button" onClick={() => { setPage("Приёмка"); }}>Результаты</button><button type="button" onClick={repeat}>Повторить задачу</button></div></aside></div></>}
    {page === "Создать задачу" && <section className="compact-panel"><p>Шаг {step + 1} из 5: {["Бриф", "Критерии и сроки", "Условия", "Поддержка", "Проверка и публикация"][step]}</p><div style={{ display: "grid", gap: 12, maxWidth: 720 }}><label>Название <input value={brief.title} onChange={(event) => { setBrief({ ...brief, title: event.target.value }); }} /></label><label>Подразделение <select value={brief.department} onChange={(event) => { setBrief({ ...brief, department: event.target.value }); }}>{["Розничный бизнес", "Клиентский сервис", "R&D"].map((item) => <option key={item}>{item}</option>)}</select></label><label>Направление <select value={brief.direction} onChange={(event) => { setBrief({ ...brief, direction: event.target.value }); }}>{["Аналитика данных", "AI / ML"].map((item) => <option key={item}>{item}</option>)}</select></label><label>Проблема и цель <textarea value={brief.problem} onChange={(event) => { setBrief({ ...brief, problem: event.target.value }); }} /></label><label>Ожидаемый результат <textarea value={brief.deliverable} onChange={(event) => { setBrief({ ...brief, deliverable: event.target.value }); }} /></label><label>Критерии успеха <textarea value={brief.criteria} onChange={(event) => { setBrief({ ...brief, criteria: event.target.value }); }} /></label><label>Дедлайн <input type="date" value={brief.deadline} onChange={(event) => { setBrief({ ...brief, deadline: event.target.value }); }} /></label><label>Мест <input type="number" min="1" value={brief.places} onChange={(event) => { setBrief({ ...brief, places: Number(event.target.value) }); }} /></label><label>Доступ <select value={brief.mode} onChange={(event) => { setBrief({ ...brief, mode: event.target.value as Task["mode"] }); }}><option value="open">Открытая задача</option><option value="invitation_only">По приглашению</option></select></label></div><p>Данные, права на результат и условия поддержки фиксируются в версии задачи перед публикацией.</p><div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}><button type="button" disabled={step === 0} onClick={() => { setStep(step - 1); }}>Назад</button><button type="button" disabled={step === 4} onClick={() => { setStep(step + 1); }}>Далее</button><button type="button" onClick={() => { saveTask(false); }}>Сохранить черновик</button><button type="button" onClick={() => { setNotice(`Предпросмотр: ${brief.title || "Без названия"} · ${brief.deliverable || "Результат не указан"}`); }}>Предпросмотр</button><button type="button" disabled={step !== 4} onClick={() => { saveTask(true); }}>Опубликовать</button></div></section>}
    {page === "Заявки" && <section className="compact-panel"><h2>Заявки на {task.title}</h2><p>Всего {state.applications.filter((item) => item.taskId === selected).length} · шорт-лист {state.applications.filter((item) => item.taskId === selected && item.status === "shortlisted").length} · назначено {state.applications.filter((item) => item.taskId === selected && item.status === "assigned").length}</p>{state.applications.filter((item) => item.taskId === selected).map((item) => { const person = state.candidates.find((candidate) => candidate.id === item.candidateId); return <article key={item.candidateId} style={{ borderTop: "1px solid #ddd", padding: 12 }}><h3>{person?.name}</h3><p>{person?.direction} · {person?.cases.map((entry) => `${entry.title}: ${entry.artifact}`).join("; ")}</p><p>Статус: {item.status}</p><div style={{ display: "flex", gap: 8 }}><button type="button" onClick={() => { updateApplication(item.candidateId, "shortlisted"); }}>В шорт-лист</button><button type="button" onClick={() => { updateApplication(item.candidateId, "waitlisted"); }}>Лист ожидания</button><button type="button" onClick={() => { updateApplication(item.candidateId, "assigned"); }}>Назначить</button></div></article>; })}{!state.applications.some((item) => item.taskId === selected) && <p>Заявок пока нет</p>}</section>}
    {page === "Приёмка" && <><div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>{state.results.map((item) => <button type="button" key={item.taskId} onClick={() => { setSelected(item.taskId); }}>{state.tasks.find((entry) => entry.id === item.taskId)?.title}</button>)}</div><section className="compact-panel"><p>Бриф → Работа → Сдача → Ревью → Приёмка</p><h2>{state.tasks.find((item) => item.id === currentResult?.taskId)?.title ?? task.title}</h2>{currentResult ? <><p>Участник: {name(state, currentResult.candidateId)}</p><p>{currentResult.summary}</p><p>Артефакты: {currentResult.artifact}</p><p>Условия версии {state.tasks.find((item) => item.id === currentResult.taskId)?.version}: {state.tasks.find((item) => item.id === currentResult.taskId)?.criteria}</p><label><input type="checkbox" /> Артефакты соответствуют ожидаемому результату</label><p>Текущее решение: {currentResult.status}</p><label>Комментарий <textarea value={comment} onChange={(event) => { setComment(event.target.value); }} /></label><div style={{ display: "flex", gap: 8 }}><button type="button" onClick={() => { setSelected(currentResult.taskId); decide("accepted"); }}>Принять</button><button type="button" onClick={() => { setSelected(currentResult.taskId); decide("revision"); }}>Вернуть на доработку</button><button type="button" onClick={() => { setSelected(currentResult.taskId); decide("disputed"); }}>Открыть спор</button></div></> : <p>Результатов пока нет</p>}</section></>}
    {page === "Аналитика" && <><div className="customer-kpi-grid">{[["Задач", state.tasks.filter((item) => item.status !== "draft").length], ["С заявками", new Set(state.applications.map((item) => item.taskId)).size], ["С результатом", new Set(state.results.map((item) => item.taskId)).size], ["Принято", accepted.length]].map(([label, value]) => <article className="compact-panel" key={label}><small>{label}</small><h2>{value}</h2></article>)}</div><section className="compact-panel"><h2>Воронка задач</h2><p>Опубликовано → Есть заявки → Назначены участники → Есть результаты → Приняты результаты</p><p>{state.tasks.filter((item) => item.status !== "draft").length} → {new Set(state.applications.map((item) => item.taskId)).size} → {new Set(state.applications.filter((item) => item.status === "assigned").map((item) => item.taskId)).size} → {new Set(state.results.map((item) => item.taskId)).size} → {accepted.length}</p><p>Время до результата: появится после фиксации дат. Экономия времени отбора: нет базы для сравнения.</p><p>Направления: Аналитика данных · AI / ML. Подразделения: Розничный бизнес · Клиентский сервис · R&D.</p></section></>}
    {page === "AI-помощник" && <section className="compact-panel"><h2>Помощь с задачей</h2><p>Подсказки требуют проверки заказчиком. Публикация и приёмка остаются его решениями.</p><div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}>{["Уточнить бриф", "Предложить критерии", "Оценить риски", "Разобрать отклики"].map((item) => <button type="button" key={item} onClick={() => { setAssistantText(item === "Уточнить бриф" ? `Проблема: ${task.problem}. Уточните исходные данные, ограничения и целевую аудиторию.` : item === "Предложить критерии" ? `Проверьте измеримые метрики: ${task.criteria}. Добавьте порог качества и формат воспроизведения.` : item === "Оценить риски" ? "Проверьте доступность данных, качество разметки, вычислительные ограничения и права на результат." : `По задаче ${task.title} поступило ${String(state.applications.filter((entry) => entry.taskId === selected).length)} заявок. Сравните подтверждённые кейсы и доступность.`); }}>{item}</button>)}</div><textarea aria-label="Рекомендация помощника" value={assistantText} onChange={(event) => { setAssistantText(event.target.value); }} style={{ width: "100%", minHeight: 130 }} /><p>Контекст: {task.title} · {status[task.status]} · дедлайн {task.deadline}</p><button type="button" onClick={() => { setAssistantText(""); }}>Очистить</button></section>}
    {page === "Кандидаты" && <section className="compact-panel"><h2>Участники с подтверждёнными кейсами</h2><p>Всего {state.candidates.length} · сохранено {state.saved.length} · приглашено {state.invited.length}</p>{state.candidates.map((person) => <article key={person.id} style={{ borderTop: "1px solid #ddd", padding: 12 }}><h3>{person.name}</h3><p>{person.direction} · {person.cases.flatMap((item) => item.skills).join(", ")}</p>{person.cases.map((item) => <p key={item.title}><strong>{item.title}</strong> · {item.artifact}</p>)}<div style={{ display: "flex", gap: 8, flexWrap: "wrap" }}><button type="button" onClick={() => { setState((current) => ({ ...current, saved: current.saved.includes(person.id) ? current.saved.filter((id) => id !== person.id) : [...current.saved, person.id] })); }}>{state.saved.includes(person.id) ? "Убрать из резерва" : "Сохранить в резерв"}</button><button type="button" onClick={() => { setState((current) => ({ ...current, invited: current.invited.includes(person.id) ? current.invited : [...current.invited, person.id] })); }}>Пригласить в задачу</button><button type="button" onClick={() => { setState((current) => ({ ...current, interviews: current.interviews.includes(person.id) ? current.interviews : [...current.interviews, person.id] })); }}>Отметить интерес к интервью</button></div><small>{state.invited.includes(person.id) ? "Приглашён · " : ""}{state.interviews.includes(person.id) ? "Интерес к интервью отмечен" : ""}</small></article>)}</section>}
    {page === "Сообщения" && <section className="compact-panel"><h2>Переписка по задаче</h2><select aria-label="Задача переписки" value={selected} onChange={(event) => { setSelected(event.target.value); }}>{state.tasks.map((item) => <option key={item.id} value={item.id}>{item.title}</option>)}</select><p>{task.department} · {status[task.status]} · срок {task.deadline}</p>{state.messages.filter((item) => item.taskId === selected).map((item, index) => <p key={`${item.author}-${String(index)}`}><strong>{item.author}:</strong> {item.body}</p>)}<label>Сообщение <textarea value={draftMessage} onChange={(event) => { setDraftMessage(event.target.value); }} /></label><button type="button" onClick={() => { if (!draftMessage.trim()) return; setState((current) => ({ ...current, messages: [...current.messages, { taskId: selected, author: "Заказчик", body: draftMessage.trim() }] })); setDraftMessage(""); }}>Отправить</button></section>}
  </main>;
}
