import { useQuery } from "@tanstack/react-query";

import { apiRequest } from "../api/client";
import { Badge, StatePanel } from "../components/ui";

type Result = { contribution_id: string; task_id: string; task_title: string; personal_summary: string; artifact_keys: string[]; reused: boolean };
type Initiative = { project_key: string; task_id: string; task_title: string; status: string; deadline_at: string | null; accepted_results: Result[] };
type Overview = { initiatives: Initiative[]; task_count: number; accepted_result_count: number; reused_result_count: number };
const demoOverview: Overview = { task_count: 12, accepted_result_count: 28, reused_result_count: 8, initiatives: [
  { project_key: "AI · Сервисы", task_id: "demo-manager-1", task_title: "AI-ассистент для сотрудников", status: "in_progress", deadline_at: "2026-10-18T18:00:00Z", accepted_results: [{ contribution_id: "demo-result-1", task_id: "demo-manager-1", task_title: "AI-ассистент для сотрудников", personal_summary: "Векторный поиск и безопасный контур ответов подготовлены для пилота.", artifact_keys: ["MVP", "API", "evaluation"], reused: true }] },
  { project_key: "Аналитика · Финансы", task_id: "demo-manager-2", task_title: "Аналитика дебиторской задолженности", status: "accepted", deadline_at: "2026-10-24T18:00:00Z", accepted_results: [{ contribution_id: "demo-result-2", task_id: "demo-manager-2", task_title: "Аналитика дебиторской задолженности", personal_summary: "Дашборд факторов риска принят бизнес-заказчиком.", artifact_keys: ["dashboard", "model-card"], reused: false }] },
  { project_key: "R&D · CV", task_id: "demo-manager-3", task_title: "Распознавание дефектов материалов", status: "in_progress", deadline_at: "2026-11-03T18:00:00Z", accepted_results: [] },
] };

export function ManagerWorkspace() {
  const query = useQuery({ queryKey: ["manager-overview"], queryFn: () => apiRequest<Overview>("/api/v1/manager/overview"), refetchOnMount: "always" });
  if (query.isLoading) return <StatePanel kind="loading" />;
  if (query.isError || !query.data) return <StatePanel kind="error" action="Повторить" onAction={() => { void query.refetch(); }} />;
  const demo = query.data.initiatives.length === 0;
  const data = demo ? demoOverview : query.data;
  const metrics: [string, string | number, string][] = [
    ["Инициативы", data.task_count, "blue"], ["Принятые результаты", data.accepted_result_count, "teal"], ["Использовано повторно", data.reused_result_count, "violet"], ["Reuse rate", data.accepted_result_count ? `${String(Math.round(data.reused_result_count / data.accepted_result_count * 100))}%` : "—", "teal"],
  ];
  return <div className="feature-stack manager-workspace"><header className="dashboard-heading"><div><p className="eyebrow">Руководитель · портфель инициатив</p><h1 id="workspace-title">Результаты команд без лишних персональных данных</h1><p className="lead">Здесь видны сроки, принятые артефакты и повторное использование. Чаты, закрытые комментарии ментора и выплаты участников недоступны.</p></div>{demo && <span className="demo-data-chip">Демо-проекция</span>}</header><section className="metric-grid" aria-label="Сводка инициатив">{metrics.map(([label, value, tone]) => <article className={`metric-card metric-card--${tone}`} key={label}><span className="metric-icon">◇</span><span>{label}</span><strong>{value}</strong><small>Безопасный агрегат · 30 дней</small><i aria-hidden="true" /></article>)}</section><div className="manager-control-grid"><section className="initiative-list" aria-labelledby="initiatives-title"><div className="section-heading"><div><p className="eyebrow">Контроль сроков</p><h2 id="initiatives-title">Инициативы и результаты</h2></div><a href="/workspace/2">Открыть аналитику →</a></div>{data.initiatives.map((item) => <article className="initiative-card" key={item.task_id}><header><div><span>{item.project_key}</span><h3>{item.task_title}</h3></div><Badge tone={item.status === "accepted" ? "success" : "neutral"}>{item.status === "accepted" ? "Принято" : "В работе"}</Badge></header><p className="muted">Дедлайн: {item.deadline_at ? new Date(item.deadline_at).toLocaleDateString("ru-RU") : "не указан"}</p>{item.accepted_results.length ? <div className="accepted-results">{item.accepted_results.map((result) => <article key={result.contribution_id}><div><strong>Принятый артефакт</strong>{result.reused && <Badge tone="success">Повторно использован</Badge>}</div><p>{result.personal_summary}</p><small>Артефакты: {result.artifact_keys.join(", ") || "зафиксированы в задаче"}</small></article>)}</div> : <p className="manager-empty">Следующий контрольный результат ожидается от команды.</p>}</article>)}</section>{demo && <aside className="manager-inspector"><section><p className="eyebrow">Быстрые действия</p><h2>Управляйте портфелем</h2><button type="button">Создать инициативу →</button><button type="button">Пригласить участника</button><button type="button">Экспортировать отчёт</button></section><section><p className="eyebrow">Статус проектов</p><div className="status-donut"><strong>12</strong><span>всего</span></div><ul><li><i className="dot-teal" />Активны <b>6</b></li><li><i className="dot-blue" />На проверке <b>3</b></li><li><i className="dot-violet" />Завершены <b>3</b></li></ul></section><section className="ai-mini"><p className="eyebrow">AI-инсайт</p><strong>2 проекта требуют внимания</strong><p>Срок контрольной точки наступит в ближайшие пять дней.</p></section></aside>}</div></div>;
}
