import { useQuery } from "@tanstack/react-query";
import { SyntheticEvent, useEffect, useMemo, useState } from "react";

import { apiRequest } from "../api/client";
import { Badge } from "../components/ui";

const settingsTabs = ["Профиль", "Безопасность", "Предпочтения", "Согласия", "Подбор", "Уведомления", "Видимость для HR", "AI-Buddy"] as const;
type SettingsTab = typeof settingsTabs[number];
type TalentConsent = "talent_profile" | "talent_evidence" | "talent_invitations" | "hr_profile";

function Toggle({ checked, label, onChange }: { checked: boolean; label: string; onChange: (value: boolean) => void }) {
  return <label className="settings-toggle"><span><strong>{label}</strong></span><input type="checkbox" checked={checked} onChange={(event) => { onChange(event.target.checked); }} /><i aria-hidden="true" /></label>;
}

export function ParticipantSettings({ actorName, consentScopes }: { actorName: string; consentScopes: string[] }) {
  const [tab, setTab] = useState<SettingsTab>("Профиль");
  const [saved, setSaved] = useState("");
  const [hrVisible, setHrVisible] = useState(consentScopes.includes("hr_profile"));
  const [buddyEnabled, setBuddyEnabled] = useState(true);
  const [consents, setConsents] = useState({ publicProfile: true, communications: false });
  const [talentConsents, setTalentConsents] = useState(() => new Set(consentScopes));
  const [talentSaving, setTalentSaving] = useState(false);
  const currentConsents = useQuery({ queryKey: ["participant-consents"], queryFn: () => apiRequest<{ consent_scopes: string[] }>("/api/v1/me"), refetchOnMount: "always" });
  useEffect(() => { if (currentConsents.data) { setTalentConsents(new Set(currentConsents.data.consent_scopes)); setHrVisible(currentConsents.data.consent_scopes.includes("hr_profile")); } }, [currentConsents.data]);
  const [visibility, setVisibility] = useState({ base: true, skills: true, projects: true, achievements: true, learning: true, contacts: false });
  const [notifications, setNotifications] = useState({ projects: true, mentors: true, payments: true, events: true, product: false, marketing: false });
  const announce = (message: string) => { setSaved(message); window.setTimeout(() => { setSaved(""); }, 2600); };
  const flip = <T extends Record<string, boolean>>(state: T, key: keyof T, setter: (next: T) => void) => { setter({ ...state, [key]: !state[key] }); };
  const updateTalentConsent = async (scope: TalentConsent, granted: boolean) => {
    setTalentSaving(true);
    try {
      const result = await apiRequest<{ granted_scopes: string[] }>(`/api/v1/me/consents/${scope}`, { method: "PUT", headers: { "X-CSRF-Token": sessionStorage.getItem("impulse_csrf") ?? "" }, body: JSON.stringify({ granted }) });
      setTalentConsents(new Set(result.granted_scopes));
      if (scope === "hr_profile") setHrVisible(granted);
      announce("Согласие обновлено");
    } catch { announce("Не удалось сохранить согласие. Повторите действие."); }
    finally { setTalentSaving(false); }
  };

  return <div className="participant-settings feature-stack">
    <header className="participant-page-heading"><div><p className="eyebrow">Личный кабинет</p><h1 id="workspace-title">Настройки</h1><p className="lead">Управляйте профилем, приватностью и тем, как платформа помогает строить карьерный путь.</p></div><button type="button" onClick={() => { announce("Настройки сохранены"); }}>Сохранить изменения</button></header>
    {saved && <div className="success-banner" role="status"><span>✓</span><div><strong>{saved}</strong><small>Изменения применены к вашему профилю.</small></div></div>}
    <div className="settings-layout"><nav className="settings-nav" aria-label="Разделы настроек">{settingsTabs.map((item) => <button className={tab === item ? "active" : ""} type="button" key={item} onClick={() => { setTab(item); }}><span>{item === "Профиль" ? "●" : item === "Безопасность" ? "◇" : item === "AI-Buddy" ? "✧" : "○"}</span>{item}</button>)}</nav>
      <main className="settings-panel">
        {tab === "Профиль" && <><div className="settings-section-title"><div><h2>Профиль участника</h2><p>Эту информацию платформа использует для рекомендаций и подбора задач.</p></div><Badge tone="success">Профиль заполнен на 86%</Badge></div><div className="profile-editor"><div className="profile-avatar">АР<button type="button" onClick={() => { announce("Окно выбора фотографии открыто"); }}>Изменить фото</button></div><div className="form-grid"><label>ФИО<input defaultValue={actorName} /></label><label>Город<input defaultValue="Москва" /></label><label>Вуз / программа<input defaultValue="МГТУ им. Н. Э. Баумана · 4 курс" /></label><label>Основное направление<select defaultValue="data"><option value="data">Аналитик данных</option><option value="python">Python-разработчик</option></select></label><label className="wide">О себе<textarea defaultValue="Развиваюсь в аналитике и backend-разработке. Хочу работать над реальными продуктами и подтверждать навыки проектами." /></label><label>Email<input type="email" defaultValue="alex@example.ru" /></label><label>Telegram<input defaultValue="@alex_data" /></label></div></div><div className="skills-editor"><h3>Ключевые навыки</h3><div>{["Python", "SQL", "FastAPI", "Аналитика данных", "OpenSpec / SDD"].map((skill) => <button type="button" key={skill} onClick={(event) => { event.currentTarget.remove(); announce(`Навык «${skill}» удалён`); }}>{skill} ×</button>)}<button className="skill-add" type="button" onClick={() => { announce("Добавлен навык «Визуализация данных»"); }}>+ Добавить навык</button></div><small>Самостоятельно добавленные навыки отмечаются как заявленные, пока не подтверждены курсом или проектом.</small></div></>}
        {tab === "Безопасность" && <><div className="settings-section-title"><div><h2>Конфиденциальность и безопасность</h2><p>Контролируйте доступ к аккаунту и активные устройства.</p></div></div><div className="settings-cards"><article><div><strong>Пароль</strong><small>Обновлён 18 дней назад</small></div><button type="button" onClick={() => { announce("Инструкция по смене пароля отправлена"); }}>Сменить пароль</button></article><article><div><strong>Двухфакторная аутентификация</strong><small>Будет доступна после подключения корпоративного провайдера</small></div><button disabled type="button">Недоступно в MVP</button></article><article><div><strong>Текущая сессия</strong><small>Windows · Chrome · Москва · сейчас</small></div><Badge tone="success">Активна</Badge></article><article><div><strong>Мобильная сессия</strong><small>Android · 27 сентября, 19:42</small></div><button type="button" onClick={(event) => { event.currentTarget.closest("article")?.remove(); announce("Сессия завершена"); }}>Завершить</button></article></div></>}
        {tab === "Предпочтения" && <><div className="settings-section-title"><div><h2>Предпочтения аккаунта</h2><p>Настройте удобное отображение платформы.</p></div></div><div className="form-grid"><label>Язык<select defaultValue="ru"><option value="ru">Русский</option><option value="en">English</option></select></label><label>Тема<select defaultValue="dark"><option value="dark">Тёмная</option><option value="system">Как в системе</option></select></label><label>Часовой пояс<select defaultValue="moscow"><option value="moscow">Москва · UTC+3</option><option value="amman">Амман · UTC+3</option></select></label></div></>}
        {tab === "Согласия" && <><div className="settings-section-title"><div><h2>Согласия и данные</h2><p>Вы сами определяете, где можно показывать профиль и достижения.</p></div></div><div className="toggle-list"><Toggle checked label="Обработка данных для работы платформы" onChange={() => { announce("Обязательное согласие можно отозвать только через удаление аккаунта"); }} /><Toggle checked={consents.publicProfile} label="Публичный профиль и достижения" onChange={() => { flip(consents, "publicProfile", setConsents); }} /><Toggle checked={consents.communications} label="Необязательные продуктовые коммуникации" onChange={() => { flip(consents, "communications", setConsents); }} /></div></>}
        {tab === "Уведомления" && <><div className="settings-section-title"><div><h2>Уведомления</h2><p>Оставьте только те сигналы, которые помогают двигаться дальше.</p></div></div><div className="toggle-list">{Object.entries({ projects: "Проекты и задачи", mentors: "Сообщения от менторов", payments: "Начисления и выплаты", events: "События", product: "Продуктовые обновления", marketing: "Маркетинговые материалы" }).map(([key, label]) => <Toggle key={key} checked={notifications[key as keyof typeof notifications]} label={label} onChange={() => { flip(notifications, key as keyof typeof notifications, setNotifications); }} />)}</div></>}
        {tab === "Видимость для HR" && <><div className="settings-section-title"><div><h2>Видимость для HR</h2><p>Откройте доказанный опыт рекрутерам и точно выберите доступные данные.</p></div><Toggle checked={hrVisible} label="Профиль доступен HR" onChange={(value) => { void updateTalentConsent("hr_profile", value); }} /></div><div className={`hr-visibility-grid${hrVisible ? "" : " disabled"}`}>{Object.entries({ base: "Базовая информация", skills: "Навыки", projects: "Проекты и оценки", achievements: "Достижения", learning: "Прогресс обучения", contacts: "Контакты" }).map(([key, label]) => <Toggle key={key} checked={visibility[key as keyof typeof visibility]} label={label} onChange={() => { flip(visibility, key as keyof typeof visibility, setVisibility); }} />)}</div><div className="hr-preview"><p className="eyebrow">Предпросмотр глазами HR</p><div><span className="profile-avatar profile-avatar--small">АР</span><div><strong>{actorName}</strong><small>Аналитик данных · 7 подтверждённых навыков</small><p>Видны проекты, сертификаты и достижения. {visibility.contacts && hrVisible ? "Контакты открыты." : "Контакты скрыты."}</p></div></div></div></>}
        {tab === "Подбор" && <><div className="settings-section-title"><div><h2>Подбор под задачи команд</h2><p>Управляйте тем, могут ли заказчики и руководители найти вас по подтверждённым кейсам.</p></div></div><fieldset disabled={talentSaving} className="toggle-list"><Toggle checked={talentConsents.has("talent_profile")} label="Показывать мой профиль в подборе" onChange={(value) => { void updateTalentConsent("talent_profile", value); }} /><Toggle checked={talentConsents.has("talent_evidence")} label="Показывать подтверждённые кейсы и разрешённые доказательства" onChange={(value) => { void updateTalentConsent("talent_evidence", value); }} /><Toggle checked={talentConsents.has("talent_invitations")} label="Получать адресные приглашения на задачи" onChange={(value) => { void updateTalentConsent("talent_invitations", value); }} /></fieldset><div className="hr-preview"><p className="eyebrow">Предпросмотр для руководителя</p><strong>{talentConsents.has("talent_profile") ? actorName : "Профиль скрыт"}</strong><p>{talentConsents.has("talent_profile") && talentConsents.has("talent_evidence") ? "Подтверждённые кейсы будут доступны после проверки релевантности запроса. Контакты и личные сообщения скрыты." : "Кейсы и доказательства скрыты."}</p><p>{talentConsents.has("talent_invitations") ? "Адресные приглашения разрешены." : "Адресные приглашения отключены."}</p></div></>}
        {tab === "AI-Buddy" && <><div className="settings-section-title"><div><h2>AI-Buddy</h2><p>Помощник объясняет следующий шаг, но не принимает решения об оценках и деньгах.</p></div><Toggle checked={buddyEnabled} label="AI-Buddy включён" onChange={setBuddyEnabled} /></div><label className="settings-select">Стиль общения<select disabled={!buddyEnabled} defaultValue="brief"><option value="brief">Кратко и по делу</option><option value="coach">Поддерживающий наставник</option><option value="detail">Подробные объяснения</option></select></label><div className="danger-zone"><div><strong>История диалога</strong><small>Очистка удалит сообщения и персональную память, но не обязательный технический аудит.</small></div><button type="button" onClick={() => { announce("История AI-Buddy очищена"); }}>Очистить историю</button></div></>}
      </main></div>
  </div>;
}

export function ParticipantBuddy() {
  const [messages, setMessages] = useState([{ from: "buddy", text: "Привет! Я вижу ваш прогресс в Python и текущий проект. Могу объяснить следующий шаг или подобрать задачу." }]);
  const [value, setValue] = useState("");
  const send = (event: SyntheticEvent<HTMLFormElement>) => { event.preventDefault(); const text = value.trim(); if (!text) return; setMessages((items) => [...items, { from: "user", text }, { from: "buddy", text: "Сейчас лучше завершить checkpoint по API: он нужен текущему проекту и подтвердит навык FastAPI. Открыть связанный модуль можно кнопкой справа." }]); setValue(""); };
  const actions = ["Что делать дальше?", "Объясни тему", "Подбери курс", "Разбери задачу", "Совет по карьере"];
  // The index is combined with the sender only for ephemeral chat rendering.
  // eslint-disable-next-line @typescript-eslint/restrict-template-expressions
  return <div className="buddy-page feature-stack"><header className="participant-page-heading"><div><p className="eyebrow">Персональный навигатор</p><h1 id="workspace-title">AI-Buddy</h1><p className="lead">Советы основаны на разрешённых данных вашего маршрута и не заменяют решения ментора.</p></div><Badge tone="warning">Бета · AI</Badge></header><div className="buddy-layout"><main className="buddy-chat"><div className="quick-prompts">{actions.map((action) => <button type="button" key={action} onClick={() => { setValue(action); }}>{action}</button>)}</div><div className="buddy-messages">{messages.map((message, index) => <article className={`buddy-message buddy-message--${message.from}`} key={`${message.from}-${index}`}><span>{message.from === "buddy" ? "✧" : "Вы"}</span><p>{message.text}</p></article>)}</div><form onSubmit={send}><input aria-label="Сообщение AI-Buddy" value={value} onChange={(event) => { setValue(event.target.value); }} placeholder="Спросите о курсе, задаче или следующем шаге…" /><button type="submit">Отправить</button></form></main><aside className="buddy-context"><p className="eyebrow">Ваш контекст</p><h2>Следующий шаг</h2><article><Badge tone="warning">Checkpoint</Badge><strong>Обработка ошибок API</strong><small>Python-разработчик · 45 минут</small><button type="button" onClick={() => { window.location.assign("/workspace/2?course=python-base"); }}>Открыть модуль →</button></article><h3>На чём основан совет</h3><ul><li>Направление: Python-разработчик</li><li>Прогресс Bootcamp: 68%</li><li>Активный проект: рекомендательная система</li><li>Цель: первый принятый вклад</li></ul><button className="secondary-button" type="button" onClick={() => { window.location.assign("/workspace/10"); }}>Написать человеку</button></aside></div></div>;
}

export function ParticipantAchievements() {
  const [filter, setFilter] = useState("Все");
  const items = useMemo(() => [{ title: "Победитель МАЯКИ 2025", kind: "Трофей", status: "Подтверждено", points: "+120" }, { title: "Python для анализа данных", kind: "Сертификат", status: "Подтверждено", points: "+80" }, { title: "AI Journey 2026", kind: "Событие", status: "На проверке", points: "+5 заморожено" }, { title: "Рекомендательная система", kind: "Проект", status: "Принято", points: "+150" }].filter((item) => filter === "Все" || item.kind === filter), [filter]);
  return <div className="achievements-page feature-stack"><header className="participant-page-heading"><div><p className="eyebrow">Проверяемые результаты</p><h1 id="workspace-title">Достижения</h1><p className="lead">Здесь собраны проекты, сертификаты и внешние победы с прозрачным статусом проверки.</p></div><button type="button" onClick={() => { window.location.assign("/workspace/5"); }}>Добавить достижение</button></header><section className="achievement-metrics"><article><span>Всего</span><strong>12</strong><small>за всё время</small></article><article><span>Подтверждено</span><strong>9</strong><small>видны в портфолио</small></article><article><span>На проверке</span><strong>2</strong><small>решение до 3 дней</small></article><article><span>Процентиль</span><strong>Топ 8%</strong><small>среди участников сезона</small></article></section><div className="achievement-toolbar">{["Все", "Событие", "Трофей", "Сертификат", "Проект"].map((item) => <button className={filter === item ? "active" : ""} type="button" key={item} onClick={() => { setFilter(item); }}>{item}</button>)}</div><section className="achievement-list">{items.map((item) => <button type="button" key={item.title} onClick={() => { window.location.assign(item.kind === "Проект" ? "/workspace/4" : item.kind === "Событие" ? "/workspace/5" : "/workspace/7"); }}><span className="achievement-icon">◆</span><div><small>{item.kind}</small><strong>{item.title}</strong><span>{item.status}</span></div><b>{item.points}</b><i>›</i></button>)}</section></div>;
}
